### ISSUE TITLE
Feature Request: Add parameter to set alpha parameter for hybrid search

### ISSUE THREAD

**Issue by ozanarmagan** [typesense/typesense#1267] opened 2023-10-02 11:29 UTC
## Description
Being able to use custom alpha param

**Comment by gustavopch** [comment] 2023-10-02 12:26
Duplicate of https://github.com/typesense/typesense/issues/1241?

**Comment by ozanarmagan** [comment] 2023-10-07 12:13
> Duplicate of #1241?

@gustavopch We plan to add this feature with upcoming release, so this issue is for tracking it internally.

**Closed** 2023-10-10 10:57 UTC
Labels: feature:vectorsearch
