### ISSUE TITLE
Crazy high text_match scores

### ISSUE THREAD

**Issue by vprelovac** [typesense/typesense#667] opened 2022-07-21 03:04 UTC
## Description

The versions of typesense post 0.22 (I think) started showing insanely high values for text_match score something like 565,161,851,158,529

Previosuly the numbers very much lower, a good match had a score of less<100,000

I am also seeing text match being the same across all hits, so something is defientely broken.

## Steps to reproduce

Check text_match score vs older version

## Expected Behavior

Have the score remain consistent

## Actual Behavior

score is much higher then it was

## Metadata

**Typsense Version**: 0.23.1

**OS**: Ubuntu

**Comment by kishorenc** [comment] 2022-07-21 10:59
> Previosuly the numbers very much lower, a good match had a score of less<100,000

The text match score is computed within Typesense by "packing" multiple text relevancy components into a 64-bit value. In 0.23 we're utilising the full breadth of that space so the scores can be larger. I would not read too much into the absolute value of these scores -- they are useful for only relative comparison. 

> I am also seeing text match being the same across all hits, so something is defientely broken.

We introduced some changes for better cross-field matching that might have caused a regression in certain other cases. I've already got an example which I've now fixed in `0.24.0.rc22` build. Would you be able to test with that? Here's the [binary](https://dl.typesense.org/releases/0.24.0.rc22/typesense-server-0.24.0.rc22-linux-amd64.tar.gz).

**Comment by vprelovac** [comment] 2022-07-21 14:29
Absolute scores are important because typsense tends to return (very) partial matches. We used absolute scores to know when a result is relevant enough (we used 100,000 threshold previously, empirically calculated).

Here is an example, running with your latest rc binary (0.24)

query: 
http acceppt json

search params:

 search_parameters = {
        "q": query,
        "query_by": "title",
        "prefix": False,
        "num_typos": 0,
        "per_page": limit,
        "limit_hits": limit,
        "typo_tokens_threshold": 0,

    }


Top results/score:

A server-side Swift HTTP web framework. (Swift) 576744423686144241
Elegant HTTP Networking in Swift (Swift) 576744423686144241
An easy and powerful Rust HTTP Client (Rust) 576744423686144241

AS you can see all the results are barely relevant for the query (they have one keyword match). In the past we could rely on text_match score to filter them out/ignore if score is >100,000.

I strongly suggest returning to pre 0.22 score calculation because it worked well.

**Comment by kishorenc** [comment] 2022-07-21 14:38
Would it be possible to post what the first 3 results are on 0.22?

**Comment by vprelovac** [comment] 2022-07-21 14:45
Is the DB backwards compatible? Concerned to lose it if I roll back to previous version of binary. It could be 0.21 too I am not sure it was 0.22 where text_maxt was changed.

**Comment by kishorenc** [comment] 2022-07-21 15:55
I will write up a detailed answer tomorrow but you should be able to rollback from 0.24 rc to 0.22 without any issues. If you wish you can do a quick test locally on a small set to confirm. New text match score introduced in 0.23.

**Comment by kishorenc** [comment] 2022-07-21 16:50
Ok if you wish to downgrade to 0.21 see this note: https://typesense.org/docs/0.22.2/api/#downgrading

**Comment by vprelovac** [comment] 2022-07-21 16:52
No, I'd like you to fix this so search works properly again :)

**Comment by kishorenc** [comment] 2022-07-22 12:18
When Typesense compares the query string with the one or more matching fields in the record, it derives a text similarity score (returned as `text_match` in the hits array in response). All the matching records are then sorted by this score for relevancy. 

Typesense uses various metrics like number of tokens matched, proximity of matched tokens, number of fields matched, field weights to compute this text similarity score. We then combine these individual metrics into a single int64 value. Over time, we've been refining and improving what metrics we use, and since 0.21, we've added more relevancy metrics so we are now fully utilising all the 64 bits. So while earlier, these scores might have been relatively small, they have grown over time and are now large because of the 64-bit nature of the values. 

> I am also seeing text match being the same across all hits, so something is defientely broken.

This recently bit me and I suspect this to be because of the JSON parser used. Many JSON parsers use IEEE754 numerical representation to store the numbers (because that's what JS does) and that does not allow you accurately store large values that are exceed 53 bits -- they end up truncating the values. Can you try looking at the raw API output without processing it with any client or `jq` etc.?

Also, in `0.24.0.rc23` build (which I just published), I've added a `text_match_info` object field that makes it easier for you to assess some of the criteria used in computing that 64-bit match score. It looks like this:

```
"text_match_info": {
    "score": "578730089005449339",         // using string to handle the JSON/JS truncation issue
    "best_field_score": "1108074561536",   
    "best_field_weight": 15,
    "fields_matched": 3,
    "tokens_matched": 1
}
```

Would this help you gauge the quality of the result?

**Comment by vprelovac** [comment] 2022-07-22 13:54
> This recently bit me and I suspect this to be because of the JSON parser used.

Note I am usingg the official Python clien, latest version.

I think there are two problems. Since 0.23 TypeSense is also returning results it previously didn't like I showed in my example. A simple fix would be to add param so the user can choose previouse matching algorithm. 

When you combine relaxed matching returning less relevant results and the inability to use text_matxt score as a quality threshold filter, you basically have search that is unusable which is current situation. I hope that makes sense.

**Comment by kishorenc** [comment] 2022-07-22 14:26
Normalising score between 0 to 1 will not help for a lot of other Typesense use cases, especially when query spreads across multiple fields like "author_name book_name" queries. In these cases having a comprehensive score view with details like I've posted above is very useful to reason about.

> Since 0.23 TypeSense is returning results that it previously didn't, results that are way less relavant, like I showed in my example. 

It would help to have a small dataset and couple of "bad queries" as reference so that I can see what's really happening and I can run locally and compare with 0.21 as well. Can you help me with that? I want to understand the root cause since nobody has yet reported huge deviations in relevance.

**Comment by vprelovac** [comment] 2022-07-22 14:30
Try adding these three titles
A server-side Swift HTTP web framework. (Swift) 
Elegant HTTP Networking in Swift (Swift) 
An easy and powerful Rust HTTP Client (Rust) 

and use the query 'http acceppt json'

with these params
search_parameters = {
"q": query,
"query_by": "title",
"prefix": False,
"num_typos": 0,
"per_page": limit,
"limit_hits": limit,
"typo_tokens_threshold": 0,

0.22 should return no results, while 0.23 will return all three.

**Comment by kishorenc** [comment] 2022-07-22 14:57
Ah I see what's happening here. In 0.21, drop tokens behavior did not fully drop until the last token. For the query `http acceppt json` it used to search for `http acceppt` and `acceppt json` so will find no results. Many users complained that Typesense should atleast fetch documents that contain atleast one of tokens in the query. So in 0.22+ we started dropping down to the last token, so now we also look for `http` which is why all 3 documents match.

If you don't like this behavior you can either send `drop_tokens_threshold: 0` (which will disable dropping of token) or in `v0.24.0.rc23` build you can check the value of `text_match_info.tokens_matched` in the hit response and have your own threshold for when to show the result. For e.g. in this case that value will be "1" and since query actually has 3 tokens you can choose not to show it.

**Comment by vprelovac** [comment] 2022-07-22 15:06
Thanks for clarifying. This change had a huge impact. Typesense result relevancy suddenly wnet from very relevant to remotely relevant. Need to be careful about making adjustments like this.

**Comment by kishorenc** [comment] 2022-08-04 09:20
Thanks for the feedback. Until we hit 1.0, each 0.x release is like a major version, while 0.x.x are the patch versions. Sometimes we are forced to break backward compatibility when we hear almost everyone wanting a particular parameter to behave in a given way. We recommend testing a portion/full dataset on a staging/dev environment before upgrading in production.

**Closed by kishorenc** 2022-08-04 09:20 UTC
