### ISSUE TITLE
Broken collection

### ISSUE THREAD

**Issue by aaronkbutler** [typesense/typesense#350] opened 2021-08-19 01:51 UTC
One of my two collections seems to no longer be accepting any curl requests towards it. Searches, collection retrievals, and even listing all collections hang and never end. However, calls that don't involve the "broken" collection work fine, like searches and collection retrievals. Any help would be greatly appreciated!

Update: searches are only broken when a specific field (called "description") is used to query_by. In addition, quitting the local server gets stuck on "Shutting down server_thread_pool."

**Comment by kishorenc** [comment] 2021-08-20 01:19
@aaronkbutler Are you able to reproduce this issue consistently even on subsequent restarts?

May I know what version of Typesense you are using and what client you are using to index?

**Comment by aaronkbutler** [comment] 2021-08-20 02:13
Seems to only happen when using the local server. I tried setting up a cluster in the Typesense cloud and that seems to work fine. Happens even after restarting the local server. I am using version 0.21.0, using curl commands in the shell.

**Comment by kishorenc** [comment] 2021-08-20 02:18
@aaronkbutler 

1. Are you saying that locally, when you "kill" the server, delete data directory and then start fresh, again the issue happens consistently? Or did it happen once and is now not recovering from that?
2. I will be happy to debug this issue with you, what timezone are you on?

**Comment by aaronkbutler** [comment] 2021-08-20 02:29
It had been resulting in the same issue after killing the server and deleting the data directory. However, it doesn't seem to be happening now. I will do some more testing to see if the issue is recreated and get back to you. Thank you for your help!

**Comment by kishorenc** [comment] 2021-08-20 02:56
Got it. Are you using Docker or a local binary (if binary, OSX or Linux)? I have an updated build which might work around this problem that i can share with you to test.

**Comment by aaronkbutler** [comment] 2021-08-20 02:59
Just got it to happen again. Seems like it happens when I follow these steps:
1. I create a new collection with auto schema detection
2. I add a new document to the collection, where one of the fields has a multi-line string
3. Any sort of query or action on involving the collection hangs

For reference, I'm using an OSX local binary.

Now that I know that it has to do with the multi-line string being the culprit, it is less of any issue for me as I can just use a pre-defined schema. However, it may be worth looking into if your interested so I'd be happy to send along any logs that could be helpful.

**Comment by kishorenc** [comment] 2021-08-20 03:22
@aaronkbutler Glad to hear that you are able to get to the bottom of it, that's half the problem solved :)

Can you please provide a sample input data or code snippet so I can reproduce it exactly? Thank you so much for helping out.

**Comment by aaronkbutler** [comment] 2021-08-20 03:25
I am writing code in Swift and using a curl library within Swift. That is the only place where I know how to create strings with line breaks (not sure how to do that in terminal).

**Comment by kishorenc** [comment] 2021-08-20 03:32
That's fine, I just need to look at how the multi-line string looks like and how it is called. A stand-alone is example should be enough for me to reproduce. Will greatly appreciate it.

**Comment by aaronkbutler** [comment] 2021-08-20 03:34
I'm not sure if I fully understand, but the kind of string is something like this:

```
This is my description
Just added a new line above
And another one there
```

**Comment by kishorenc** [comment] 2021-08-20 03:53
Is it possible for you post the CURL library snippet as well? Even if it is a library level issue, we might still need to handle that edge case so that others don't face it.

**Comment by kishorenc** [comment] 2021-08-20 04:01
I just tried to reproduce this issue with a multi-line string on other clients, but unable to do so. So a quick Swift code snippet showing the collection creation and a write that triggers the issue would be great. Sorry to bother!

**Comment by aaronkbutler** [comment] 2021-08-20 22:19
I first made the new collection from the terminal like this:
` curl "http://localhost:8108/collections" \
       -X POST \         
       -H "Content-Type: application/json" \ 
       -H "X-TYPESENSE-API-KEY: MYAPIKEY" \ 
       -d '{            
  "name": "products",
  "fields": [                  
    {                                
      "name": ".*",
      "type": "auto"
    }                                      
  ]            
}'  `

Then in Swift all I am doing is adding a new document to my Firestore database, which then, using the Firebase Typesense extension, is added over to my Typesense server. A sample curl command that hang (both in the terminal and in my iOS app) looks like this:
`curl -H "X-TYPESENSE-API-KEY: MYAPIKEY" "http://localhost:8108/collections/products/documents/search?q=test&query_by=title,team,description,league,sport,playerName&page=1"
`
I hope this helps.

**Comment by kishorenc** [comment] 2021-08-21 00:17
You said that this issue was happening on local server right? How is the Firestore extension able to write to your localhost?

Would you be free sometime for a 15 min call so you can screenshare and show this issue live to me? That would be super helpful and help us fix a issue that will help many others in future. I've simply not been able to reproduce this otherwise despite trying several variations of a auto schema with multi line strings.

**Comment by aaronkbutler** [comment] 2021-08-22 00:43
I’d be happy to call.

**Comment by kishorenc** [comment] 2021-08-22 13:33
@aaronkbutler Thanks, I really appreciate that. Please pick a time that's convenient for you: https://calendly.com/kishorenc/30min

I look forward to chatting & getting to the bottom of this issue!

**Comment by kishorenc** [comment] 2021-08-23 03:42
This turned out to be an OSX specific issue which was not reproduceable on my mac. However, the latest `0.22.rc5` build no longer exhibits this issue, so we should be good in future. 

Closing this for now, thank you for helping in debug this @aaronkbutler.

**Closed by kishorenc** 2021-08-23 03:42 UTC
