### ISSUE TITLE
[Feature request] Support update documents filter by query

### ISSUE THREAD

**Issue by SagareGanesh** [typesense/typesense#258] opened 2021-04-19 06:55 UTC
It will be good if we provide support to update the documents filter by query

Example
```
  product_schema = {
     "name" =>  "products",
     "fields" => [
         { "name" => "name", "type" => "string" },
         { "name" => "available_months",  "type" => "string[]" },
         ........
       ]
    }
```
In the above schema, there is no way to update all such products that have empty available months

**Comment by kishorenc** [comment] 2021-04-19 13:42
👍 This is already on our road map. I agree that this would be useful to have an update by query end-point.

**Comment by psucodervn** [comment] 2021-08-30 18:18
Hi @kishorenc , are there any updates on this?

**Comment by kishorenc** [comment] 2022-12-19 07:33
Duplicate of https://github.com/typesense/typesense/issues/496

**Closed by kishorenc** 2022-12-19 07:33 UTC
Labels: enhancement
