### ISSUE TITLE
USD symbol works in symbols_to_index but EUR / GBP symbols do not

### ISSUE THREAD

**Issue by philefstat** [typesense/typesense#1752] opened 2024-05-24 13:37 UTC
## Description

USD symbol works in symbols_to_index but EUR / GBP symbols do not

## Steps to reproduce

1. Create a collection with `symbols_to_index: ['$']` , it works
2. Create a collection with `symbols_to_index: ['£']` or  `symbols_to_index: ['€']`, it throws an error 
```RequestMalformed: Request failed with HTTP code 400 | Server said: `symbols_to_index` should be an array of character symbols.```

## Expected Behavior

Would expect it to work for other major currency symbols, not just USD

## Actual Behavior

```RequestMalformed: Request failed with HTTP code 400 | Server said: `symbols_to_index` should be an array of character symbols.```

## Metadata

**Typesense Version**: 0.26 (local docker)

**OS**: Mac

**Comment by unclescooby** [comment] 2024-07-30 00:00
Possibly related: https://github.com/typesense/typesense/issues/875

**Comment by kishorenc** [comment] 2024-07-30 07:59
Yeah, the problem is that we don't support multi-byte separator strings. The original goal was to support simple ASCII punctuation and all of them are single byte characters so that's what the system supports.Here, `$` is an ASCII character but the other currency symbols are not. 

Closing in favor of https://github.com/typesense/typesense/issues/875

**Closed by kishorenc** 2024-07-30 07:59 UTC
