### ISSUE TITLE
Add q parameter to export method

### ISSUE THREAD

**Issue by redaben** [typesense/typesense#848] opened 2023-01-05 16:26 UTC
## Description

Today, the export method allows filter_by parameter. It should be great if the export method also allow the q (query) parameter.

## Expected Behavior

client.collections('companies').documents().export({ q, filter_by })

**Comment by jasonbosco** [comment] 2023-05-10 19:45
Duplicate of #485

**Closed by jasonbosco** 2023-05-10 19:45 UTC
Labels: enhancement, feature:filtering
