### ISSUE TITLE
Implement infix/suffix searching for specific fields

### ISSUE THREAD

**Issue by TatuUlmanen** [typesense/typesense#393] opened 2021-09-28 22:51 UTC
## Description

Currently Typesense can not find results if the search term isn't at the beginning of the word (prefix search). For example, the search query "DEF" would not return result "ABCDEF", but "ABC" would.

Suffix search would solve the problem when the searched term is at the end of the word, but that would still miss results where the searched string is neither at the start or the end of the word. Suffix search is apparently also complex to implement.

As a simpler approach, a form of brute force searching could be enabled on a field by field basis. Brute force searching quickly becomes a bottleneck on larger datasets, but when dealing with "smaller" data, this might be viable. For example, when a field contains only short strings, the search could complete in a reasonable time. It would be up to the user to enable brute force searching, knowing the trade offs.

As a real life example, a product has the code 157B2210. This product should be returned when the search query is B2210 or even B22, if brute force searching is enabled.

A workaround was suggested for the meantime: each character combination (substring) could be split into an array field and the search performed against that. But even a ten character long string has 55 unique substrings so the amount of data would get unnecessarily large if a better solution could be found.

**Comment by jasonbosco** [comment] 2022-03-11 18:20
This is available as of `0.23.0.rc43`:

**Usage**

Since infix searching requires an additional data structure, you have to enable it on a per-field basis like this:

```
{"name": "part_number", "type": "string", "infix": true }
```

During searching, infix searching can be enabled on a per-field basis by sending a comma separated string parameter called `infix` to the search query. This parameter can have 3 values:

- off
- always
- fallback

`off`: infix search is disabled, which is default
`always`: infix search is performed along with regular search
`fallback`: infix search is performed if regular search does not produce results

For e.g. if you are querying two fields, `query_by=title,part_number` and to enable infix searching only for the part_number field, you can send: `?infix=off,always` (same order of fields as `query_by`).

There are also 2 parameters that allow you to control the extent of infix searching:

`max_extra_prefix` and `max_extra_sufix` which specify the maximum number of symbols before or after the query that can be present in the token. For example: query "K2100" has 2 extra symbols in "6PK2100". By default, any number of prefixes/suffixes can be present for a match.

**Comment by shandyDev** [comment] 2022-03-30 16:22
Pay attention, it is feature very, very increase CPU-bound (and speed searching decrease). 
Our example (3 nodes by 8vCPU google c2 instances): usual daily load vs with enable infix search param - https://i.imgur.com/gksY3WL.png different almost in 5 times...

**Comment by kishorenc** [comment] 2022-03-31 15:11
@shandyDev Yes, unfortunately there are no shortcuts to infix searching -- there are no efficient data structures to do this cheap. We recommend enabling it only on specific fields like model/part numbers and using infix searching in the fallback mode.

**Comment by shandyDev** [comment] 2022-03-31 15:29
If compare ElasticSearch (1 field with wildcard) VS Typesense 1 field with always infix, I believe Easticsearch will WIN this battle (by search response time).  If will some time will make real tests)
This is despite the fact that we migrated from Elasticsearch to Typesense because without infix Typesense double win )

**Comment by kishorenc** [comment] 2022-03-31 15:40
Can you provide an example of the Elasticsearch field type and query you are making? Happy to compare and see if there is something we can do to improve.

**Comment by shandyDev** [comment] 2022-03-31 16:08
More ways to settings - it always cool! )
And yes, add more memory - cheaper (I mean cloud) then add vCPUs (and BTW high load traffic for CPU-bound always worse).

**Comment by kishorenc** [comment] 2022-04-05 06:29
@shandyDev 

Here's an alternative way to implement the same **without** relying on the new `infix` feature.

Let's say there is a field called `model_number` whose values you want to be infix searchable. Example value:

```
"model_number":  "TH123Y"
```

Index this field as an array of n-grams:

```
"model_number_array": ["TH123Y", "H123Y", "123Y", "23Y", "3Y", "Y]
```

Now, you can do a regular prefix search on this field and it will be match any infix value and it will be really fast!  E.g. `H123` will prefix match `H123Y`, `23` will prefix match `23Y` and so on. This approach is suitable for shorter strings, while the `infix` approach which we have implemented is suited for larger strings.

Let me know what you think.

**Comment by shandyDev** [comment] 2022-04-05 07:39
> for larger strings

Yes, it is actually our case. If try build field as an array of n-grams then the index will be inflated a lot (ok, maybe we will ready to pay for it), and second we have many variative number set (with repeating n-grams parts), like: `123Y`, `GH3223YAA`, `87623Y8`, so on. When search by  `23Y` all this will be found. But relevant (at least first result) should be `123Y` and I don't think what search by model_number_array will sort like this.

We will experiment on this further...

**Comment by Grolribasi** [comment] 2022-05-30 06:56
Hi! We have a similar use case.

We use Typesense on our docs site that contains API reference. But API is searchable only if you know what to search, see example below.  

For example if we search for `SessionSuspendTimeout` it will return the docs containing the "SessionSuspendTimeout". But if we search for `SuspendTimeout` or `Timeout` or even `Suspend` the same results won't appear in the search. 

It can be hard for users to remember the start of the parameter name, they may not remember the complete phrasing.

Is it possible to enable search inside of the compond words? Splitting API into smaller fields, obviously, is a bad option.

If there is any possible way, please, direct me to it. I'm not a developer, I just want to know if it possible and, if it is possible, I will forard it to developers.

**Comment by kishorenc** [comment] 2022-05-30 07:19
@Grolribasi 

Yes, suffix/infix search is possible on 0.23 RC builds if it's enabled in the field schema. See the `infix` query parameter in this table: https://github.com/typesense/typesense-website/blob/050a8bb7f1f3553974d24a7ec4a538542b461c1b/docs-site/content/0.23.0/api/documents.md#query-parameters

**Comment by Grolribasi** [comment] 2022-05-30 07:29
Thank you @kishorenc !

**Closed** 2022-06-19 05:25 UTC
Labels: enhancement

**Comment by Grolribasi** [comment] 2022-06-22 07:37
@kishorenc Can you please clarify one more question? As I understand, the function only works when performing field search, so fields must be created. But is it possible to perform the infix search through the whole site? I mean, just do infix search for plain text?

Creating fields for every API description on two thousand plus pages of documentation site is a tough thing to do.

**Comment by kishorenc** [comment] 2022-06-26 03:22
@Grolribasi I don't follow you. You have to enable infix searching at a field level using the `infix: true` property in the collection schema. You can have a field that just stores the text you need and enable infix searching on that. However, this feature is memory intensive and is meant to be used only on identifiers like phone numbers, product IDs, email addresses, etc. I would not recommend enabling it on large text fields.

**Comment by Grolribasi** [comment] 2022-06-27 06:49
@kishorenc Sorry for not being clear enough. I'm having trouble understanding what a field is? I can guess that it's a some kind of div with a special class. Am I right?

**Comment by kishorenc** [comment] 2022-06-27 07:23
@Grolribasi Please see this getting started tutorial which talks about what collections and fields are in Typesense: https://typesense.org/docs/guide/building-a-search-application.html#creating-a-books-collection

For further questions, please ask in our [Slack community](https://join.slack.com/t/typesense-community/shared_invite/zt-mx4nbsbn-AuOL89O7iBtvkz136egSJg) so that we can keep this issue relevant to only infix search discussion.

**Comment by rog1039** [comment] 2022-09-13 14:14
Just wondering if this was implemented via extra CPU usage during search or via n-grams during indexing with increased memory size? In our case we would much, much prefer to have a higher index size via n-grams than increased CPU usage/latency during search.

**Comment by rog1039** [comment] 2022-09-13 14:57
👍 Thanks for the update.

**Comment by ArminShoeibi** [comment] 2025-11-10 21:08
Hi there @kishorenc , @jasonbosco,

The lack of a `Farsi` tokenizer creates major issues, especially with compound words and infix searches.

A key challenge is handling compound words. For example, a user searching for `پیراشکی `should find it in both the compound form `پودرخمیرپیراشکی` (one token) and the spaced form `پودر خمیر پیراشکی` (three tokens). This is complicated by the use of spaces, ZWNJ, and ZWJ, which are not handled correctly by the current tokenization.

Our current workaround is a 1-gram search. While this can match characters inside a compound token, it fails catastrophically by ignoring token order. This leads to massively irrelevant results, like matching `پ و د ر خ م ی ر` against a completely unrelated product simply because it contains the same letters scattered throughout. We're forced to do complex, inefficient post-processing to filter out the noise.

The core issue is that infix search is not working for Farsi, nor for Arabic. For these languages, an effective infix search essentially is a 1-gram search, but one that understands token ordering, series, and context, something that's currently missing for farsi and arabic.

The ideal solution is native infix support for a Farsi locale, which would handle tokenization and matching correctly on the server side, eliminating the need for these client-side hacks.

I'm keen to help develop this. A formal proposal would be a great start. Thanks for considering it.

**Comment by kishorenc** [comment] 2025-11-11 07:30
I'm surprised that `پیراشکی` is not matching the compound form via prefix search. Can you create a small reproducible example in this format: https://gist.github.com/jasonbosco/7c3432713216c378472f13e72246f46b

**Comment by ArminShoeibi** [comment] 2025-11-11 11:08
> I'm surprised that `پیراشکی` is not matching the compound form via prefix search. Can you create a small reproducible example in this format: https://gist.github.com/jasonbosco/7c3432713216c378472f13e72246f46b

<img width="1149" height="1124" alt="Image" src="https://github.com/user-attachments/assets/34dacea6-8cc2-4a7b-96a9-d917402368fd" />

```
پودرخمیرپیراشکی↵
پودر•خمیر•پیراشکی↵
پودر⟨ZWNJ⟩خمیر⟨ZWNJ⟩پیراشکی
```
The first is a true compound, no spaces, no ZWNJ, so search engines read it as one token.

The second has spaces between all three words. It's the most natural, grammatically correct form.

The third looks like the first but functions like the second. The ZWNJ keeps it visually tight while making each word searchable. For languages with this complexity, both the second and third work fine.


Reproduce:

<img width="2052" height="1040" alt="Image" src="https://github.com/user-attachments/assets/a9591b36-af79-4307-babb-c7035952e61e" />

<img width="1125" height="913" alt="Image" src="https://github.com/user-attachments/assets/8c151639-7ada-4540-9a63-771a728fb0a1" />

<img width="2072" height="870" alt="Image" src="https://github.com/user-attachments/assets/c9b23547-f3d7-42cd-a73b-4faffbb28c15" />

for curl(s) and reproduce script, I will do it and attach to this issue ASAP, but for now I just uploaded some pics for fast response.

@kishorenc

**Comment by ArminShoeibi** [comment] 2025-12-22 10:59
> I'm surprised that `پیراشکی` is not matching the compound form via prefix search. Can you create a small reproducible example in this format: https://gist.github.com/jasonbosco/7c3432713216c378472f13e72246f46b

I found out that I should send `"infix":"always,..."` in each request with for the specified field.
thanThanks your response, and it works.
