### ISSUE TITLE
Result found attribute shows wrong count

### ISSUE THREAD

**Issue by snuzi** [typesense/typesense#105] opened 2020-05-02 11:57 UTC
## Description
Search result `found` attribute is bigger then the number of stored documents
[Describe the issue here]
I have 1k documents and when searching by a keyword the `found` shows 1.3k
Or when there is only one result, it shows `found: 19`

## Expected Behavior

Should tell me the number of found results for that query.
## Actual Behavior

`found` result attribute is greater then total number of indexed documents.
## Metadata

**Typsense Version**:  `0.11.2`

**OS**: Ubuntu

**Comment by kishorenc** [comment] 2020-05-03 02:59
@snuzi To help troubleshoot this, can you please:

1. Paste the schema of the collection here? You can replace the field names with placeholders if that matters.

2. The full HTTP query URL or the exact client code which produces the anomalies.

**Comment by snuzi** [comment] 2020-05-03 12:38
Collection schema:
```json
{"fields":[{"name":"id","type":"string"},{"name":"_id","type":"int32"},{"name":"ingredients","type":"string[]"},{"name":"categories","type":"string[]","facet":true},{"name":"cuisines","type":"string[]","facet":true},{"name":"instructions","type":"string[]"},{"name":"description","type":"string"},{"name":"notes","type":"string"},{"name":"name","type":"string"},{"name":"image","type":"string"},{"name":"cookingMethod","type":"string"},{"name":"prepTime","type":"string"},{"name":"totalTime","type":"string"},{"name":"cookTime","type":"string"},{"name":"publisher","type":"string"},{"name":"author","type":"string"},{"name":"url","type":"string"},{"name":"yield","type":"string"}],"default_sorting_field":"_id"}
```

Query params:
```json
{"q":"garlic","query_by":"name,description,notes,ingredients,instructions","facet_by":"cuisines,categories","include_fields":"name,id,_id,url"}
```
I am using this client [devloopsnet/typesense-php](https://github.com/devloopsnet/typesense-php)
```php
$client->collections[$this->indexName]->documents->search($params)
```

**Comment by snuzi** [comment] 2020-05-03 12:42
Please find some data for indexing here
```json
{"author":"Jamie Oliver","categories":["Desserts","Fruit","Easter treats","New Year party picks","Halloween recipes","Bonfire night recipes","Christmas"],"cookingMethod":null,"cookTime":null,"cuisines":{"3":"Dairy-free","4":"Vegan","5":"Vegetarian"},"description":"Hot, crisp and sweet, these doughnuts are a fantastic sweet treat that everyone will love","image":"http:\/\/cdn.jamieoliver.com\/recipe-database\/oldImages\/xtra_med\/1332_1_1436866373.jpg","ingredients":["sunflower oil","baking powder","salt","icing sugar","orange","vanilla pod"],"instructions":["Melt the margarine, soya milk and 2 tablespoons of the sunflower oil in a small pan over a medium heat. Meanwhile, combine the flour, baking powder, salt and sugar in a large bowl. Make a well in the middle, then tip in the melted mixture.","Gradually bring the mixture together with a fork until it forms a wet, thick dough, then divide and roll into 24 golf-ball sized balls.","Heat the remaining sunflower oil in a medium-sized deep pan over a high heat. To test if the oil is hot enough, drop a piece of bread into the pan - if the bread floats to the surface, sizzles and turns golden, it's about right. Reduce the heat to medium, then use a slotted spoon to carefully lower six dough balls into the hot oil. Cook for 3 to 5 minutes, or until golden, cooked through and they've floated to the surface, turning occasionally.","Meanwhile, make the vanilla sugar. Halve the vanilla pod lengthways and scrape out the seeds. Bash the seeds and half the sugar in a pestle and mortar, then place into a large bowl with the remaining sugar.","Transfer the cooked doughnuts to a double layer of kitchen paper to drain. Allow to cool for a few minutes, roll in the vanilla sugar to coat, then place on a tray. Repeat with the remaining dough balls.","Meanwhile, make the raspberry dip. Place the raspberries, icing sugar and a squeeze of orange juice into a bowl, then crush well with the back of a fork. Serve the mini doughnuts with the raspberry dip, then tuck in!"],"name":"Mini vegan doughnuts","notes":null,"prepTime":null,"publisher":null,"totalTime":50,"url":"https:\/\/www.jamieoliver.com\/recipes\/fruit-recipes\/mini-vegan-doughnuts\/","yield":"24","nutrition":{"calories":87,"fat":5,"fiber":0.6,"protein":1.2,"sugar":5.9},"nameSub":"With a quick raspberry dip","ingredientList":{"ingredients":[{"name":"sunflower oil","measure":{"amount":6,"name":"whole","cups":0}},{"name":"baking powder","measure":{"amount":1.5,"name":"teaspoons","cups":0.062499}},{"name":"salt","comment":"sea","measure":{"amount":0.5,"name":"teaspoon","cups":0.020833}},{"name":"icing sugar","measure":{"amount":1,"name":"tablespoon","cups":0.125}},{"name":"orange","measure":{"amount":0.5,"name":"whole","cups":1}},{"name":"vanilla pod","measure":{"amount":1,"name":"whole","cups":0}}],"ingredientLines":[{"LineOriginal":"1.5 litres sunflower oil","Line":" 1 5 litres sunflower oil ","IngredientsInString":[{"Word":"sunflower oil","Position":11}],"AmountInString":[{"Word":"1","Position":0},{"Word":"5","Position":2}],"Ingredient":{"name":"sunflower oil","measure":{"amount":6,"name":"whole","cups":0}}},{"LineOriginal":"1\u00bd teaspoons baking powder","Line":" 1  \u00bd  teaspoons baking powder ","IngredientsInString":[{"Word":"baking powder","Position":17}],"AmountInString":[{"Word":"1","Position":0},{"Word":"\u00bd","Position":3}],"MeasureInString":[{"Word":"teaspoons","Position":7}],"Ingredient":{"name":"baking powder","measure":{"amount":1.5,"name":"teaspoons","cups":0.0312495}}},{"LineOriginal":"\u00bd teaspoon sea salt","Line":"  \u00bd  teaspoon sea salt ","IngredientsInString":[{"Word":"salt","Position":18}],"AmountInString":[{"Word":"\u00bd","Position":1}],"MeasureInString":[{"Word":"teaspoon","Position":5}],"Ingredient":{"name":"salt","comment":"sea","measure":{"amount":0.5,"name":"teaspoon","cups":0.0104165}}},{"LineOriginal":"1 heaped tablespoon icing sugar","Line":" 1 heaped tablespoon icing sugar ","IngredientsInString":[{"Word":"icing sugar","Position":20}],"AmountInString":[{"Word":"1","Position":0}],"MeasureInString":[{"Word":"tablespoon","Position":9}],"Ingredient":{"name":"icing sugar","measure":{"amount":1,"name":"tablespoon","cups":0.0625}}},{"LineOriginal":"\u00bd orange","Line":"  \u00bd  orange ","IngredientsInString":[{"Word":"orange","Position":5}],"AmountInString":[{"Word":"\u00bd","Position":1}],"Ingredient":{"name":"orange","measure":{"amount":0.5,"name":"whole","cups":0.5}}},{"LineOriginal":"1 vanilla pod","Line":" 1 vanilla pod ","IngredientsInString":[{"Word":"vanilla pod","Position":2}],"AmountInString":[{"Word":"1","Position":0}],"Ingredient":{"name":"vanilla pod","measure":{"amount":1,"name":"whole","cups":0}}}]},"_id":1}
```
```json
{"author":"Jamie Oliver","categories":["Mains","Jamie's Comfort Food","Chicken","Father's day","American","Chicken thighs"],"cookingMethod":null,"cookTime":null,"cuisines":["american"],"description":"This is an incredible fried chicken recipe, one that I've subtly evolved from that of my dear friend Art Smith, one of the kings of southern American comfort food. I've finished the chicken in the oven, purely because you really do need a big fryer to do it properly, as well as for good temperature control, and this method is much friendlier for home cooking.","image":"http:\/\/cdn.jamieoliver.com\/recipe-database\/oldImages\/xtra_med\/1356_1_1440772046.jpg","ingredients":["chicken thighs","chicken","sweet potatoes","baking powder","cayenne pepper","smoked paprika","onion powder","garlic powder","oil","black peppercorns","thyme","bay leaves","cloves","fennel seeds","caster sugar","cabbage"],"instructions":["To make the brine, toast the peppercorns in a large pan on a high heat for 1 minute, then add the rest of the brine ingredients and 400ml of cold water. Bring to the boil, then leave to cool, topping up with another 400ml of cold water.","Meanwhile, slash the chicken thighs a few times as deep as the bone, keeping the skin on for maximum flavour. Once the brine is cool, add all the chicken pieces, cover with clingfilm and leave in the fridge for at least 12 hours - I do this overnight.","After brining, remove the chicken to a bowl, discarding the brine, then pour over the buttermilk, cover with clingfilm and place in the fridge for a further 8 hours, so the chicken is super-tender.","When you're ready to cook, preheat the oven to 190\u00b0C\/375\u00b0F\/gas 5.","Wash the sweet potatoes well, roll them in a little sea salt, place on a tray and bake for 30 minutes.","Meanwhile, make the pickle - toast the fennel seeds in a large pan for 1 minute, then remove from the heat. Pour in the vinegar, add the sugar and a good pinch of sea salt, then finely slice and add the cabbage. Place in the fridge, remembering to stir every now and then while you cook your chicken.","In a large bowl, mix the flour with the baking powder, cayenne, paprika and the onion and garlic powders.","Just under half fill a large sturdy pan with oil - the oil should be 8cm deep, but never fill your pan more than half full - and place on a medium to high heat. Use a thermometer to tell when it's ready (180\u00b0C), or add a piece of potato and wait until it turns golden - that's a sign it's ready to go.","Take the chicken out of the fridge, then, one or two pieces at a time, remove from the buttermilk and dunk into the bowl of flour until well coated. Give them a shake, then place on a large board and repeat with the remaining chicken pieces.","Turn the oven down to 170\u00b0C\/325\u00b0F\/gas 3 and move the sweet potatoes to the bottom shelf.","Once the oil is hot enough, start with 2 thighs - quickly dunk them back into the flour, then carefully lower into the hot oil using a slotted spoon. Fry for 5 minutes, turning halfway, then remove to a wire rack over a baking tray.","Bring the temperature of the oil back up, repeat the process with the remaining 2 thighs, then pop the tray into the oven.","Fry the 4 drumsticks in one batch, then add them to the rack of thighs in the oven for 30 minutes, or until all the chicken is cooked through.","Serve with your baked sweet potatoes, cabbage pickle and some salad leaves."],"name":"Southern fried chicken","notes":null,"prepTime":null,"publisher":null,"totalTime":135,"url":"https:\/\/www.jamieoliver.com\/recipes\/chicken-recipes\/southern-fried-chicken\/","yield":"4","nutrition":{"calories":523,"fat":13.9,"fiber":0,"protein":27,"sugar":23.6},"nameSub":"With red cabbage pickle","ingredientList":{"ingredients":[{"name":"chicken thighs","measure":{"amount":4,"name":"whole","cups":0}},{"name":"chicken","measure":{"amount":4,"name":"whole","cups":24}},{"name":"sweet potatoes","measure":{"amount":4,"name":"whole","cups":0}},{"name":"baking powder","measure":{"amount":1,"name":"teaspoon","cups":0.041666}},{"name":"cayenne pepper","measure":{"amount":1,"name":"teaspoon","cups":0.041666}},{"name":"smoked paprika","comment":"hot","measure":{"amount":1,"name":"teaspoon","cups":0.041666}},{"name":"onion powder","measure":{"amount":1,"name":"teaspoon","cups":0.041666}},{"name":"garlic powder","measure":{"amount":1,"name":"teaspoon","cups":0.041666}},{"name":"oil","measure":{"amount":2,"name":"whole","cups":0}},{"name":"black peppercorns","measure":{"amount":1,"name":"tablespoon","cups":0.125}},{"name":"thyme","measure":{"amount":4,"name":"whole","cups":8}},{"name":"bay leaves","measure":{"amount":4,"name":"whole","cups":0}},{"name":"cloves","measure":{"amount":4,"name":"whole","cups":0}},{"name":"fennel seeds","measure":{"amount":1,"name":"teaspoon","cups":0.041666}},{"name":"caster sugar","comment":"golden","measure":{"amount":1,"name":"tablespoon","cups":0.125}},{"name":"cabbage","measure":{"amount":0.5,"name":"whole","cups":1}}],"ingredientLines":[{"LineOriginal":"4 free-range chicken thighs, skin on, bone in","Line":" 4 free range chicken thighs skin on bone in ","IngredientsInString":[{"Word":"chicken thighs","Position":13},{"Word":"skin","Position":28},{"Word":"bone","Position":36}],"AmountInString":[{"Word":"4","Position":0}],"Ingredient":{"name":"chicken thighs","measure":{"amount":4,"name":"whole","cups":0}}},{"LineOriginal":"4 free-range chicken drumsticks","Line":" 4 free range chicken drumsticks ","IngredientsInString":[{"Word":"chicken","Position":13}],"AmountInString":[{"Word":"4","Position":0}],"Ingredient":{"name":"chicken","measure":{"amount":4,"name":"whole","cups":12}}},{"LineOriginal":"4 sweet potatoes","Line":" 4 sweet potatoes ","IngredientsInString":[{"Word":"sweet potatoes","Position":2}],"AmountInString":[{"Word":"4","Position":0}],"Ingredient":{"name":"sweet potatoes","measure":{"amount":4,"name":"whole","cups":0}}},{"LineOriginal":"1 level teaspoon baking powder","Line":" 1 level teaspoon baking powder ","IngredientsInString":[{"Word":"baking powder","Position":17}],"AmountInString":[{"Word":"1","Position":0}],"MeasureInString":[{"Word":"teaspoon","Position":8}],"Ingredient":{"name":"baking powder","measure":{"amount":1,"name":"teaspoon","cups":0.020833}}},{"LineOriginal":"1 level teaspoon cayenne pepper","Line":" 1 level teaspoon cayenne pepper ","IngredientsInString":[{"Word":"cayenne pepper","Position":17}],"AmountInString":[{"Word":"1","Position":0}],"MeasureInString":[{"Word":"teaspoon","Position":8}],"Ingredient":{"name":"cayenne pepper","measure":{"amount":1,"name":"teaspoon","cups":0.020833}}},{"LineOriginal":"1 level teaspoon hot smoked paprika","Line":" 1 level teaspoon hot smoked paprika ","IngredientsInString":[{"Word":"smoked paprika","Position":21}],"AmountInString":[{"Word":"1","Position":0}],"MeasureInString":[{"Word":"teaspoon","Position":8}],"Ingredient":{"name":"smoked paprika","comment":"hot","measure":{"amount":1,"name":"teaspoon","cups":0.020833}}},{"LineOriginal":"1 level teaspoon onion powder","Line":" 1 level teaspoon onion powder ","IngredientsInString":[{"Word":"onion powder","Position":17}],"AmountInString":[{"Word":"1","Position":0}],"MeasureInString":[{"Word":"teaspoon","Position":8}],"Ingredient":{"name":"onion powder","measure":{"amount":1,"name":"teaspoon","cups":0.020833}}},{"LineOriginal":"1 level teaspoon garlic powder","Line":" 1 level teaspoon garlic powder ","IngredientsInString":[{"Word":"garlic powder","Position":17}],"AmountInString":[{"Word":"1","Position":0}],"MeasureInString":[{"Word":"teaspoon","Position":8}],"Ingredient":{"name":"garlic powder","measure":{"amount":1,"name":"teaspoon","cups":0.020833}}},{"LineOriginal":"2 litres groundnut oil","Line":" 2 litres groundnut oil ","IngredientsInString":[{"Word":"oil","Position":19}],"AmountInString":[{"Word":"2","Position":0}],"Ingredient":{"name":"oil","measure":{"amount":2,"name":"whole","cups":0}}},{"LineOriginal":"1 tablespoon black peppercorns","Line":" 1 tablespoon black peppercorns ","IngredientsInString":[{"Word":"black peppercorns","Position":13}],"AmountInString":[{"Word":"1","Position":0}],"MeasureInString":[{"Word":"tablespoon","Position":2}],"Ingredient":{"name":"black peppercorns","measure":{"amount":1,"name":"tablespoon","cups":0.0625}}},{"LineOriginal":"4 sprigs of fresh thyme","Line":" 4 sprigs of fresh thyme ","IngredientsInString":[{"Word":"thyme","Position":18}],"AmountInString":[{"Word":"4","Position":0}],"Ingredient":{"name":"thyme","measure":{"amount":4,"name":"whole","cups":4}}},{"LineOriginal":"4 fresh bay leaves","Line":" 4 fresh bay leaves ","IngredientsInString":[{"Word":"bay leaves","Position":8}],"AmountInString":[{"Word":"4","Position":0}],"Ingredient":{"name":"bay leaves","measure":{"amount":4,"name":"whole","cups":0}}},{"LineOriginal":"4 cloves of garlic","Line":" 4 cloves of garlic ","IngredientsInString":[{"Word":"cloves","Position":2},{"Word":"garlic","Position":12}],"AmountInString":[{"Word":"4","Position":0}],"Ingredient":{"name":"cloves","measure":{"amount":4,"name":"whole","cups":0}}},{"LineOriginal":"1 teaspoon fennel seeds","Line":" 1 teaspoon fennel seeds ","IngredientsInString":[{"Word":"fennel seeds","Position":11}],"AmountInString":[{"Word":"1","Position":0}],"MeasureInString":[{"Word":"teaspoon","Position":2}],"Ingredient":{"name":"fennel seeds","measure":{"amount":1,"name":"teaspoon","cups":0.020833}}},{"LineOriginal":"1 heaped tablespoon golden caster sugar","Line":" 1 heaped tablespoon golden caster sugar ","IngredientsInString":[{"Word":"caster sugar","Position":27}],"AmountInString":[{"Word":"1","Position":0}],"MeasureInString":[{"Word":"tablespoon","Position":9}],"Ingredient":{"name":"caster sugar","comment":"golden","measure":{"amount":1,"name":"tablespoon","cups":0.0625}}},{"LineOriginal":"\u00bd red cabbage, (500g)","Line":"  \u00bd  red cabbage ","IngredientsInString":[{"Word":"cabbage","Position":9}],"AmountInString":[{"Word":"\u00bd","Position":1}],"Ingredient":{"name":"cabbage","measure":{"amount":0.5,"name":"whole","cups":0.5}}}]},"_id":2}
```
```json
{"author":"Jamie Oliver","categories":["Jamie's cook and save","Dinner Party","Australia day","Mains","BBQ food"],"cookingMethod":null,"cookTime":null,"cuisines":["australian"],"description":"Juicy, marinated lamb chops with a fresh, crunchy Arabian-style salad - this is an absolute joy","image":"http:\/\/cdn.jamieoliver.com\/recipe-database\/oldImages\/xtra_med\/1326_2_1437999522.jpg","ingredients":["lamb","breads","lettuce","mint","cucumber","tomatoes","lemon","paprika"],"instructions":["Preheat the oven to 200\u00baC\/400\u00baF\/gas 6.","Trim and discard any thick pieces of fat from the lamb chops, drizzle with a little olive oil and season with sea salt and black pepper.","Tear the pitta breads into small pieces, spread out on a baking tray and bake in the oven for 10 to 12 minutes, or until golden and crisp.","Meanwhile, quarter and roughly chop the sweet crunch lettuce, discarding any tatty outer leaves, then place in a large bowl along with the rocket.","Peel and halve the cucumber lengthways, scoop out the seeds, then halve lengthways again, cut into small chunks and add to the bowl.","Roughly chop the tomatoes and add to the bowl. Pick the mint leaves, discarding the stalks, then keep aside for later.","Preheat the grill, griddle pan or barbecue to a medium heat and cook the lamb chops for 3 minutes on each side for a nice, pink, juicy chop, or a little longer if you like your meat well done, then remove to a plate to rest.","Add the pitta pieces to the bowl of salad with the mint leaves, reserving a few of the smaller leaves.","Squeeze over the lemon juice, drizzle over 3 tablespoons of extra virgin olive oil and add a pinch of salt and pepper, then toss together.","Sprinkle over the paprika and the reserved mint leaves, then serve with the lamb chops, drizzled with the resting juices."],"name":"Grilled lamb chops with fattoush","notes":["Make a delicious super-quick tzatziki-style dip by spooning a few dollops of natural yoghurt into a small bowl, adding a squeeze of lemon juice, \u00bd a deseeded and finely chopped cucumber, a little chopped mint, a pinch of salt and pepper and a drizzle of extra virgin olive oil."],"prepTime":null,"publisher":null,"totalTime":35,"url":"https:\/\/www.jamieoliver.com\/recipes\/lamb-recipes\/grilled-lamb-chops-with-fattoush\/","yield":"4","nutrition":{"calories":409,"fat":22.4,"fiber":0,"protein":33.9,"sugar":4.5},"nameSub":"Pittas & salad","ingredientList":{"ingredients":[{"name":"lamb","measure":{"amount":4,"name":"g","cups":0.04}},{"name":"breads","measure":{"amount":2,"name":"whole","cups":0}},{"name":"lettuce","measure":{"amount":1,"name":"whole","cups":2}},{"name":"mint","measure":{"amount":0.5,"name":"whole","cups":0.0208333}},{"name":"cucumber","measure":{"amount":0.5,"name":"whole","cups":1}},{"name":"tomatoes","measure":{"amount":3,"name":"whole","cups":0}},{"name":"lemon","measure":{"amount":1,"name":"whole","cups":2}},{"name":"paprika","measure":{"amount":0.5,"name":"teaspoon","cups":0.020833}}],"ingredientLines":[{"LineOriginal":"4 x 100 g lamb chops","Line":" 4 x 100 g lamb chops ","IngredientsInString":[{"Word":"lamb","Position":10}],"AmountInString":[{"Word":"4","Position":0}],"MeasureInString":[{"Word":"g","Position":8}],"Ingredient":{"name":"lamb","measure":{"amount":4,"name":"g","cups":0.02}}},{"LineOriginal":"2 wholemeal pitta breads","Line":" 2 wholemeal pitta breads ","IngredientsInString":[{"Word":"breads","Position":18}],"AmountInString":[{"Word":"2","Position":0}],"Ingredient":{"name":"breads","measure":{"amount":2,"name":"whole","cups":0}}},{"LineOriginal":"1 sweet crunch lettuce","Line":" 1 sweet crunch lettuce ","IngredientsInString":[{"Word":"lettuce","Position":15}],"AmountInString":[{"Word":"1","Position":0}],"Ingredient":{"name":"lettuce","measure":{"amount":1,"name":"whole","cups":1}}},{"LineOriginal":"\u00bd a bunch of fresh mint","Line":"  \u00bd  a bunch of fresh mint ","IngredientsInString":[{"Word":"mint","Position":22}],"AmountInString":[{"Word":"\u00bd","Position":1}],"Ingredient":{"name":"mint","measure":{"amount":0.5,"name":"whole","cups":0.01041665}}},{"LineOriginal":"\u00bd a cucumber","Line":"  \u00bd  a cucumber ","IngredientsInString":[{"Word":"cucumber","Position":7}],"AmountInString":[{"Word":"\u00bd","Position":1}],"Ingredient":{"name":"cucumber","measure":{"amount":0.5,"name":"whole","cups":0.5}}},{"LineOriginal":"3 ripe tomatoes","Line":" 3 ripe tomatoes ","IngredientsInString":[{"Word":"tomatoes","Position":7}],"AmountInString":[{"Word":"3","Position":0}],"Ingredient":{"name":"tomatoes","measure":{"amount":3,"name":"whole","cups":0}}},{"LineOriginal":"1 lemon","Line":" 1 lemon ","IngredientsInString":[{"Word":"lemon","Position":2}],"AmountInString":[{"Word":"1","Position":0}],"Ingredient":{"name":"lemon","measure":{"amount":1,"name":"whole","cups":1}}},{"LineOriginal":"\u00bd teaspoon paprika, or sumac","Line":"  \u00bd  teaspoon paprika or sumac ","IngredientsInString":[{"Word":"paprika","Position":14},{"Word":"sumac","Position":25}],"AmountInString":[{"Word":"\u00bd","Position":1}],"MeasureInString":[{"Word":"teaspoon","Position":5}],"Ingredient":{"name":"paprika","measure":{"amount":0.5,"name":"teaspoon","cups":0.0104165}}}]},"_id":3}
```
```json
{"author":"Jamie Oliver","categories":["Mains","Jamie Magazine","Vegetables","Christmas","Dinner Party","Thanksgiving","Italian"],"cookingMethod":null,"cookTime":null,"cuisines":{"1":"Vegetarian"},"description":"Sticky, roasted veggies on creamy polenta, served with wild mushroom sauce and horseradish cr\u00e8me fra\u00eeche - this is pure indulgence","image":"http:\/\/cdn.jamieoliver.com\/recipe-database\/oldImages\/xtra_med\/1349_1_1414431302.jpg","ingredients":[],"instructions":["Preheat the oven to 190\u00baC\/375\u00baF\/gas 5. Find the largest roasting tin that will fit in your oven.","Scrub the beetroots, halving or quartering any larger ones. Peel and smash the garlic, then place in a bowl, pick in the thyme leaves and combine with the balsamic and a lug of olive oil. Season well with sea salt and black pepper, then tip into one corner of the roasting tray.","Cut the squash into wedges, then deseed. Crush the coriander seeds and chilli, then peel and smash the garlic. Place in the same bowl, then strip in the rosemary and toss together with the cinnamon stick and a lug of olive oil, and season. Tip into another part of the roasting tray.","Peel the carrots and parsnips, then pick over the thyme leaves. Toss with the zest and juice of the clementines and a splash of olive oil. Tip into another part of the roasting tray.","Peel and cut the celeriac into wedges. Crush the fennel seeds and tear the sage, then toss with the celeriac and a little olive oil and add to the roasting tray, again keeping it separate.","Peel and halve the red onions, toss with the thyme leaves, balsamic and a little olive oil, then add to the roasting tray.","Wash the turnips, tear the bay leaves, then toss with a lug of olive oil and a nice grating of nutmeg. Add to the roasting tray, ensuring each veg group is not too clumped together in the tray.","Cover the tray with tin foil and roast in the oven for 50 minutes, or until the vegetables are tender and golden, removing the foil for the last 20 minutes.","For the horseradish cr\u00e8me fra\u00eeche, finely grate the horseradish into a bowl, then mix with the cr\u00e8me fra\u00eeche, 1 tablespoon of extra virgin olive oil and a squeeze of lemon juice. Season to taste and set aside.","To make the wild mushroom sauce, place a large frying pan over a high heat and pour in a couple of lugs of olive oil. Tip in the mushrooms, tearing any larger ones, and give it a shake to coat them in the oil. Cook for 5 minutes, or until beginning to soften.","Peel, finely slice and add the garlic, and strip in the thyme leaves. Give the pan a good shake and cook for 4 minutes, or until the mushrooms are coloured, then add the butter and a squeeze of lemon juice.","Reduce the heat to medium-low and stir in the cream, adding a splash of water to loosen to you desired consistency, if needed.","To make the polenta, pour 2 litres of water in a large pan and bring it to the boil over a medium heat. Slowly pour in the polenta in a steady stream, whisking until incorporated. Continue stirring over the heat for 10 minutes, or until it easily comes away from the edge of the pan.","Stir in the butter and grate in the Parmesan, beating until creamy and adding a splash of water to get it to the right consistency, if needed.","Season the polenta to taste, then immediately pour it onto a large board or platter and scatter over a few chunks of Stilton. Toss the roasted veg in their cooking juices, then spoon them over the polenta.","Scatter over the celery leaves, a grating of truffle or a drizzle of truffle oil (if using) and spoon over any remaining juices from the tray. Delicious with mostarda di Cremona and salsa verde."],"name":"Veggie arrosto misto","notes":["Mostarda di Cremona is a candied fruit preserve which you can buy from Italian delis. Acorn squash is dark green with a nutty flavour - feel free to swap in butternut squash if you can't find it."],"prepTime":null,"publisher":null,"totalTime":80,"url":"https:\/\/www.jamieoliver.com\/recipes\/vegetables-recipes\/veggie-arrosto-misto\/","yield":"8 to 10","nutrition":{"calories":726,"fat":40.1,"fiber":0,"protein":18,"sugar":20.5},"nameSub":"With truffle polenta","ingredientList":{"ingredients":[],"ingredientLines":[]},"_id":4}
```

**Comment by kishorenc** [comment] 2020-05-03 14:36
@snuzi 

I am not able to reproduce the issue with that query from CURL. Can you please try the following steps:

1. Create a collection:

```
curl "http://localhost:8108/collections" -X POST -H "Content-Type: application/json" \
      -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -d'{"name": "recipes", "fields":[{"name":"id","type":"string"},{"name":"_id","type":"int32"},{"name":"ingredients","type":"string[]"},{"name":"categories","type":"string[]","facet":true},{"name":"cuisines","type":"string[]","facet":true},{"name":"instructions","type":"string[]"},{"name":"description","type":"string"},{"name":"notes","type":"string"},{"name":"name","type":"string"},{"name":"image","type":"string"},{"name":"cookingMethod","type":"string"},{"name":"prepTime","type":"string"},{"name":"totalTime","type":"string"},{"name":"cookTime","type":"string"},{"name":"publisher","type":"string"},{"name":"author","type":"string"},{"name":"url","type":"string"},{"name":"yield","type":"string"}],"default_sorting_field":"_id"}'
```

2. Put these documents in a `recipes.jsonl` file: https://gist.github.com/kishorenc/e6dd68ec072fe99f627b57087be80521

3. Import the documents onto the collection created:

```
curl -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -X POST --data-binary @recipes.jsonl 'http://localhost:8108/collections/recipes/documents/import'
```

4. Now query the collection as follows (be sure to replace the API key):

```
http://localhost:8108/collections/recipes/documents/search?q=garlic&query_by=name,description,notes,ingredients,instructions&facet_by=cuisines,categories&include_fields=name,id,_id,url&x-typesense-api-key=<YOUR API KEY HERE>
```

The `found` field only shows 2 records. Please note that I had to make some changes to the input documents field above since the sample documents you posted did not match the schema.

If you can share a larger dataset with me, that will help a lot. If you can just zip your typesense data directory, that would suffice. Maybe you can email it to me privately: contact@typesense.org

**Comment by kishorenc** [comment] 2020-05-20 15:55
On further email conversation, this was not reproduceable. Will close it for now.

**Closed by kishorenc** 2020-05-20 15:55 UTC
Labels: bug, triage

**Comment by ddanielou** [comment] 2026-08-20 15:57
@kishorenc I'm also randomly, and extremely rarely, getting too large `found` counts on my results, which messes with pagination.

I can reproduce it on multiple Typesense installs, though.

Can I email the dataset to you privately? It's not super sensitive data but I'd rather not share it publicly.
