### ISSUE TITLE
instant search adapter flattens grouped results

### ISSUE THREAD

**Issue by majestiq** [typesense/typesense#1115] opened 2023-07-25 14:49 UTC
## Description

when using a group by query with the instantsearch adapter, the results will be flattened.  ie: groupLimit = 4 means that I will have # of results per page X 4 results showing on the page.

## Expected Behavior

Only show the first items from the group and allow secondary items in the group to be access via an array in the Hits object rendering.  That way, from the Hits widget, we can put in custom rendering to decide how to handle additional items in a group.

**Comment by jasonbosco** [comment] 2023-07-26 01:42
Duplicate of https://github.com/typesense/typesense-instantsearch-adapter/issues/178

**Closed by jasonbosco** 2023-07-26 01:42 UTC
