### ISSUE TITLE
Accept null for fieldtype auto and string*

### ISSUE THREAD

**Issue by unclescooby** [typesense/typesense#401] opened 2021-10-08 21:13 UTC
## Description

Fieldtype auto and string* do not accept null values. As all other optional fields now accept null, it would make sense that auto and string* behave the same.

## Steps to reproduce

Put any of these in the schema:

`["name" => "foo", "type" => "string*" ]`
`["name" => "foo.*", "type" => "string*" ]`
`["name" => "foo.*", "type" => "auto" ]`
`["name" => ".*", "type" => "string*" ]`
`["name" => ".*", "type" => "auto" ]`

then index a value `"foo" => null`

## Expected Behavior

Ignore null values. Index the rest of the document. Don't create a new schemafield. It can be created as soon as an acceptable value comes in.

## Actual Behavior

Typesense seems eager to create a schema field, but since it cannot determine a data type it throws an error and aborts indexing the document (potential data loss).

## Metadata

**Typsense Version**: 0.12.0 rcs12

**OS**: Linux Centos 7

**Comment by kishorenc** [comment] 2021-10-09 15:18
@unclescooby Should be fixed in [`0.12.0 rcs13`](http://dl.typesense.org/releases/0.22.0.rcs13/typesense-server-0.22.0.rcs13-linux-amd64.tar.gz).

**Comment by unclescooby** [comment] 2021-10-10 00:27
This is a big improvement. No error and no schema gets created. However, it does index or store the null value (for these fieldtype only).

**Comment by kishorenc** [comment] 2021-10-10 01:13
I don't follow. You mean it does *not* index or store the null value?

**Comment by unclescooby** [comment] 2021-10-10 01:29
I mean it DOES index null values, instead of discarding them. That's for auto and string* fields only. For the other fieldtypes null values are discarded as expected.

**Comment by kishorenc** [comment] 2021-10-10 14:54
Ok got it, I have a fix for this but will produce a build along with some other changes in a day or two for verification.

**Comment by kishorenc** [comment] 2021-10-12 08:30
@unclescooby Please try with [`0.12.0 rcs14`](http://dl.typesense.org/releases/0.22.0.rcs14/typesense-server-0.22.0.rcs14-linux-amd64.tar.gz).

**Comment by unclescooby** [comment] 2021-10-14 16:57
Yeah that fixed it.

**Comment by unclescooby** [comment] 2021-11-11 18:00
In retrospect: it looks like some people like to index NULL values #266 #435 and it looks like that rcs14+ no longer indexes NULL values for any schema field, and I don't want to be the one who triggered the loss of that feature. And yes the title of this issue and what I wrote were unclear. With "accept" I meant to say don't throw an error. My main concern was that sending NULL to auto/string* field was throwing an error and causing the document not to be indexed. PERIOD. So what I wanted is that in such particular case the NULL value be ignored and the rest of the document be indexed. For all other cases whereever possible it should index NULL as requested by some of your users...

**Comment by kishorenc** [comment] 2021-11-12 09:14
@unclescooby This is not a regression introduced by recent changes. Even on 0.21, `null` values are dropped prior to indexing. With updates, this is a problem because, now you end up not changing the old document by completely ignoring the `null` valued fields.

Closing this issue again, but please re-open if I am missing something here.

**Closed by kishorenc** 2021-11-12 09:14 UTC
