### ISSUE TITLE
Server Returns 404 When Trying to Update Schema Field

### ISSUE THREAD

**Issue by becauseinterwebs** [typesense/typesense#638] opened 2022-06-29 15:30 UTC
## Description

According to the docs (https://typesense.org/docs/0.23.0/api/collections.html#update-or-alter-a-collection) a to alter a field in an existing schema you have to drop it and add it back in the same operation.  Following the example in the docs always returns a "Not found" message.

## Steps to reproduce

Alter a field in the collection:

Note: The SERVER and KEY variables DO hold the correct server address and key.

curl "https://${SERVER}/collections/contacts" \
       -X PATCH \
       -H "Content-Type: application/json" \
       -H "X-TYPESENSE-API-KEY: ${KEY}" \
       -d '{
         "fields": [
           {"name": "gender", "type": "string", "drop": true }
           {"name": "gender", "type": "string", "facet": true, "index": true, "optional": true }   
         ]
       }'

## Expected Behavior

Schema should be updated.

## Actual Behavior

Always receive a "not found" message and schema is not updated.

{ "message": "Not Found"}

## Metadata

**Typsense Version**: 0.23.0

**OS**: Linux

**Comment by kishorenc** [comment] 2022-06-30 11:05
@becauseinterwebs 

I'm not able to reproduce this in a simple example. The `404` error usually happens if the collection is somehow missing -- are you sure that the `contacts` collection exists on that server? You can hit the `/collections/contacts` end-point to verify this.

If you can create a complete stand-alone example of this issue, including the initial collection creation step, I will be happy to look further.

**Comment by becauseinterwebs** [comment] 2022-06-30 15:33
Here is an example.  I did run it against my server and am receiving the 404.  Thank you!

https://github.com/becauseinterwebs/typesense-example

**Comment by kishorenc** [comment] 2022-06-30 15:45
Just to confirm, you are using Typesense 0.23.0 verison right? You can hit the /debug endpoint to confirm that.

**Comment by kishorenc** [comment] 2022-07-01 09:34
@becauseinterwebs 

I'm not able to reproduce. 

Here's a curl version of your example that runs successfully for me here: https://gist.github.com/kishorenc/d95096f014a3278753f29d5840d939dc

Are you able to run it successfully? If so, the issue might be something to do with the JS client.

**Comment by stri8ed** [comment] 2022-07-01 14:29
I am experiencing the same issue. Running a GET request against the collection name, returns the collection. But attempting a PATCH request, returns 404. I am issues these requests via Postman.

**Comment by jasonbosco** [comment] 2022-07-01 14:54
@stri8ed 

> I'm running 0.22.0.rcs25. Perhaps it's time to update.

v0.23.0 of Typesense server is the version that introduced schema updates. So you definitely want to upgrade to use this feature.

**Comment by jasonbosco** [comment] 2022-07-01 16:26
That’s correct, schema updates only landed in a later RC. I’d recommend using the GA version `0.23.0`.

**Comment by becauseinterwebs** [comment] 2022-07-01 16:38
Ok great thank you I'll get it upgraded.

**Closed** 2022-07-05 03:53 UTC
