### ISSUE TITLE
how can i implement typesence in android 

### ISSUE THREAD

**Issue by FaisalThreestops** [typesense/typesense#956] opened 2023-03-29 06:46 UTC
## Description

i did intgrate typesence in android using java client . but authentication is not working. its showing some error

## Steps to reproduce

>> https://github.com/typesense/typesense-java
>>Build.gradle 
implementation 'org.typesense:typesense-java:0.0.10'

>> Main activity
val nodes: MutableList<Node> = ArrayList<Node>()
        nodes.add(
            Node(
                "https",  // For Typesense Cloud use https
                BuildConfig.NEXT_PUBLIC_TYPESENSE_HOST,  // For Typesense Cloud use xxx.a1.typesense.net
                "443" // For Typesense Cloud use 443
            )
        )
 val configuration = Configuration(nodes, Duration.ofSeconds(2), BuildConfig.NEXT_PUBLIC_TYPESENSE_APIKEY)
        val client = Client(configuration)

Accessing hidden method Ljava/lang/invoke/LambdaMetafactory;->metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; (blacklist, linking, denied)
12:16:13.215  W  ERROR StatusLogger Unable to load services for service class org.apache.logging.log4j.spi.Provider
12:16:13.215  W   java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.runtime/javalib/core-oj.jar)
12:16:13.216  W  	at org.apache.logging.log4j.util.ServiceLoaderUtil.callServiceLoader(ServiceLoaderUtil.java:109)
12:16:13.216  W  	at org.apache.logging.log4j.util.ServiceLoaderUtil$ServiceLoaderSpliterator.<init>(ServiceLoaderUtil.java:145)
12:16:13.216  W  	at org.apache.logging.log4j.util.ServiceLoaderUtil.loadClassloaderServices(ServiceLoaderUtil.java:100)
12:16:13.216  W  	at org.apache.logging.log4j.util.ServiceLoaderUtil.loadServices(ServiceLoaderUtil.java:82)
12:16:13.216  W  	at org.apache.logging.log4j.util.ServiceLoaderUtil.loadServices(ServiceLoaderUtil.java:76)
12:16:13.216  W  	at org.apache.logging.log4j.util.ProviderUtil.<init>(ProviderUtil.java:67)
12:16:13.216  W  	at org.apache.logging.log4j.util.ProviderUtil.lazyInit(ProviderUtil.java:145)
12:16:13.216  W  	at org.apache.logging.log4j.util.ProviderUtil.hasProviders(ProviderUtil.java:129)
12:16:13.216  W  	at org.apache.logging.log4j.LogManager.<clinit>(LogManager.java:90)
12:16:13.216  W  	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:598)
12:16:13.216  W  	at org.typesense.api.ApiCall.<clinit>(ApiCall.java:33)
12:16:13.217  W  	at org.typesense.api.Client.<init>(Client.java:28)

12:16:13.223  W  ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
12:16:13.231  W  Accessing hidden method Ljava/lang/invoke/LambdaMetafactory;->metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; (blacklist, linking, denied)

**Comment by kishorenc** [comment] 2023-03-31 07:30
Duplicate of https://github.com/typesense/typesense-java/issues/32

**Closed by kishorenc** 2023-03-31 07:30 UTC
