### ISSUE TITLE
Exact match not getting higher score than incomplete match. 

### ISSUE THREAD

**Issue by dingusagar** [typesense/typesense#247] opened 2021-03-22 15:40 UTC
## Description

The search fields of my collection has "Kashmir", "Azad Kashmir". 
When the search query is "Kashmir", the score on "Azad Kashmir" is more than that of "Kashmir"

## Steps to reproduce
the collection schema looks like 
```
 'fields': [
      {'name': 'city_synonyms', 'type': 'string[]'},
  ]

```
the documents in the collection looks like 
```
{
    "city_synonyms": ["Kashmir" ],
},
{
    "city_synonyms": ["Azad Kashmir" ],
},
```
search params: 
```
{
     'q' : 'Kashmir',
      'query_by': 'city_synonyms',
      'sort_by': '_text_match:desc',
}
```

## Expected Behavior

Expected to get a text match score on the document having "Kashmir"  higher than the rest of the documents. 

## Actual Behavior
The text match score on the document containing "Azad Kashmir" is higher than the score on the document containing "Kashmir"

## Metadata

**Typsense Version**: 0.19.0  

**OS**: Ubuntu 20 LTS

**Comment by kishorenc** [comment] 2021-03-23 11:43
Duplicate of https://github.com/typesense/typesense/issues/191 -- will get fixed soon!

**Closed by kishorenc** 2021-03-23 11:43 UTC
