### ISSUE TITLE
Link Collections to other Collections

### ISSUE THREAD

**Issue by e-lobo** [typesense/typesense#598] opened 2022-05-22 12:51 UTC
## Description

Can we link Collections to other collections by ID and obtain the information.. kind of like how Graphql queries are structured..? 

Let me explain..

Say we have 2 collections

```
Products {
          id
          product_name: string
          category: string
}
```

```
Category{
          id
          category_name
         ...various other fields...
}
```

We have the following 2 Categories

```
{
          id: 1,
          category_name: "Fruits"
}
```

```
{
          id: 2,
          category_name: "Car"
}
```

And we have the following 2 Product documents

```
{
          id: 1,
          product_name: "Apple"
          category: 1     <== this is a link to Category Collection id 1
}
```

```
{
          id: 2,
          product_name: "BMW"
          category: 2    <== this is a link to Category Collection id 2
}
```

So it would be really helpful if we can fetch the products and expand upon categories.. something like

```
search_parameters = {
    'q': '',
    'page': 1,
    'per_page': 5,
    'include_fields': 'product_name, category'
    'nested_fields': 'category.category_name'    <=== suggested field
}
client.collections['products'].documents.search(search_parameters)
```

and the response would be...

```
[
{
          id: 1,
          product_name: "Apple"
          category: {
              id: 1,
              category_name: "Fruits"
          }
},
{
          id: 2,
          product_name: "BMW"
          category: {
              id: 2,
              category_name: "Car"
          }
}
]
```

**Comment by kishorenc** [comment] 2022-05-24 15:54
It's not possible to do this at the moment. This requires us to implement a "join" feature which SQL database support. We've this on our long term roadmao.

**Comment by e-lobo** [comment] 2022-06-24 11:54
ok thanks 👍

**Comment by jasonbosco** [comment] 2022-10-06 16:43
Duplicate of #229

**Closed by jasonbosco** 2022-10-06 16:43 UTC
