### ISSUE TITLE
Feature Request: Total Facet Counts

### ISSUE THREAD

**Issue by sanchaz** [typesense/typesense#290] opened 2021-06-11 06:10 UTC
## Description

I want to know if there are more facets so I can give the user a visual queue that there are more options than what I am showing. 

Currently we can set max_facet_values, but we have no way to know there are more facets than those returned.

Current workaround is to not set max_facet_values and restrict what we show in the UI. But that means we are potentially returning a lot of information from typesense that is useless.

## Expected Behavior

Similar to how found let's us know the number of results for hits even if we have per_page set.

found_facets would give us the total number of facets found, even if max_facet_values is set.

**Comment by nojvek** [comment] 2021-08-13 07:04
Seems like a dupe of #273

**Comment by kishorenc** [comment] 2021-08-19 16:17
Yes, closing in favor of #273 but I can now see how this will be useful. Maybe we can do it optionally as suggested in the other ticket.

**Closed by kishorenc** 2021-08-19 16:17 UTC
