### ISSUE TITLE
Results are missing

### ISSUE THREAD

**Issue by pierre-H** [typesense/typesense#443] opened 2021-11-23 23:30 UTC
## Description

I have an element in which there is `string[]` field with these values : 
```json
[
  "002313121",
  "002313135",
  "002313134"
 ]
```
Searching for `23131` gives no result but with `023131`, the element is founded.

## Steps to reproduce

Search with `23131`. I tried the `exhaustive_search=true` new parameter of the `0.22` version but still nothing.

## Expected Behavior

The element should be found.

## Actual Behavior

The element is not found.

## Metadata

**Typsense Version**: 0.22 rcs 34 from Docker

**OS**: Debian

**Comment by jasonbosco** [comment] 2021-11-23 23:35
@pierre-H This is the current expected behavior, since Typesense only supports prefix searches at the moment. More context here: https://github.com/typesense/typesense/issues/393

That issue description also mentions a workaround at the end. 

Could you subscribe to that issue to get updates? I'll close this issue, since it's a duplicate of #393.

**Closed** 2021-11-23 23:35 UTC
