### ISSUE TITLE
Cryptyc error about file creation on startup

### ISSUE THREAD

**Issue by honzasterba** [typesense/typesense#1955] opened 2024-09-18 20:35 UTC
## Description

When starting a typesense instance with the following command:

docker run --detach --restart unless-stopped 
--log-opt max-size="10m" 
--env-file .kamal/env/accessories/slave.env  # contains API key ENV var
--env TYPESENSE_API_PORT="8108" 
--env TYPESENSE_PEERING_PORT="8107" 
--env TYPESENSE_PEERING_SUBNET="10.11.0.0/16" 
--env TYPESENSE_DATA_DIR="/data" 
--env TYPESENSE_THREAD_POOL_SIZE="32" 
--env TYPESENSE_HEALTHY_READ_LAG="100000" 
--env TYPESENSE_HEALTHY_WRITE_LAG="5000" 
--env TYPESENSE_NUM_DOCUMENTS_PARALLEL_LOAD="10000" 
--env TYPESENSE_NUM_COLLECTIONS_PARALLEL_LOAD="128" 
--env TYPESENSE_NODES="/nodes.txt"
--volume $PWD/slave/nodes.txt:/nodes.txt 
--volume $PWD/slave/data:/data 
--label service="slave"
--cpus "4" --memory "30GB" --publish "28108:8108" --network "swarm_net" 
typesense/typesense:27.0

I get this error in the output:

I20240918 20:20:22.386423     1 store.cpp:40] Initializing DB by opening state dir: /data/db
I20240918 20:20:22.542657     1 store.cpp:40] Initializing DB by opening state dir: /data/meta
I20240918 20:20:22.550940     1 store.cpp:40] Initializing DB by opening state dir:
E20240918 20:20:22.551378     1 store.cpp:54] Error while initializing store: IO error: No such file or directory: While mkdir if missing: No such file or directory
E20240918 20:20:22.551398     1 store.cpp:56] It seems like the data directory  is already being used by another Typesense server.

There is no other process using the directory. I have tried manually deleting the LOCK files after stopping the server. None of that would help. What directory is it trying to create and why is it failing?

## Expected Behavior

there is no error

## Metadata

**Typesense Version**: 0.27

**OS**: docker/swarm

**Comment by kishorenc** [comment] 2024-09-19 03:04
The root cause is because we now accept an analytics directory path for the analytics db but if it's not provided, we try to open with an empty path and since that fails, an error is logged. But this should not affect any regular operations.

This is fixed in `28.0.rc7` and will also be part of upcoming `27.1` release.

**Closed by kishorenc** 2024-09-19 03:04 UTC
