### ISSUE TITLE
Crash during facet population

### ISSUE THREAD

**Issue by mubibil** [typesense/typesense#146] opened 2020-11-02 00:36 UTC
Hi, 
After upgrade from 0.15 to 0.16 Typesense keeps crashing. Log file is too complicated for me :) Screenshot:
<img width="1210" alt="Ekran Resmi 2020-11-02 03 21 02" src="https://user-images.githubusercontent.com/72962877/97819836-1c59ab00-1cbc-11eb-870d-6be7bad60a4a.png">

## Metadata

**Typsense Version**: 0.16

**OS**:Centos 7

**Comment by kishorenc** [comment] 2020-11-02 01:52
@mubibil From the log, the issue is happening during the facet population step of searching. Can you post the schema used for this collection (feel free to use pseudo names for the fields if that matters), and the actual search query with the faceting that is sent (if you are able to isolate the search query causing the crash)?

**Comment by mubibil** [comment] 2020-11-02 09:17
@kishorenc 

1. Yes, I am using update feature.
2. I have 12 facet fields, so it is hard to guess which causing the crash. 
Schema: 
`["name"=>"tag","type"=>"string[]","facet"=>true],
["name"=>"cat","type"=>"string[]","facet"=>true],
["name"=>"sub","type"=>"string[]","facet"=>true],
["name"=>"size","type"=>"string[]","facet"=>true],
["name"=>"color","type"=>"string[]","facet"=>true],
["name"=>"type","type"=>"string[]","facet"=>true],
["name"=>"style","type"=>"string[]","facet"=>true],
["name"=>"material","type"=>"string[]","facet"=>true]
["name"=>"brand","type"=>"string","facet"=>true],
["name"=>"provider","type"=>"string","facet"=>true],
["name"=>"price_range","type"=>"string","facet"=>true],
["name"=>"discount_range","type"=>"string[]","facet"=>true],`
Non filtered query:
`/collections/xxxxxx/documents/search?max_hits=all&prefix=false&drop_tokens_threshold=0&typo_tokens_threshold=2&highlight_full_fields=name&per_page=60&page=1&sort_by=popularity:desc&q=*&num_typos=1&query_by=product_tags&facet_by=cat,sub,type,material,style,color,price_range,size,discount_range,brand,provider,tag&max_facet_values=1000`
Filtered query:
`[root] => /collections/xxxxxx/documents/search?max_hits=all&prefix=false&drop_tokens_threshold=0&typo_tokens_threshold=2&highlight_full_fields=name&per_page=60&page=1&sort_by=popularity:desc&q=*&num_typos=1&query_by=product_tags&facet_by=cat,sub,type,material,style,color,price_range,size,discount_range,brand,provider,tag&max_facet_values=1000&filter_by=material:[Triko,Dantel]%26%26style:[Askılı,Crop Top]`
`[material] => /collections/xxxxxx/documents/search?max_hits=all&prefix=false&drop_tokens_threshold=0&typo_tokens_threshold=2&highlight_full_fields=name&per_page=0&page=1&sort_by=popularity:desc&q=*&num_typos=1&query_by=product_tags&max_facet_values=1000&facet_by=material&filter_by=style:[Askılı,Crop Top]`
`[style] => /collections/xxxxxx/documents/search?max_hits=all&prefix=false&drop_tokens_threshold=0&typo_tokens_threshold=2&highlight_full_fields=name&per_page=0&page=1&sort_by=popularity:desc&q=*&num_typos=1&query_by=product_tags&max_facet_values=1000&facet_by=style&filter_by=material:[Triko,Dantel]`

I hope this helps

**Comment by kishorenc** [comment] 2020-11-02 13:07
@mubibil 

Thanks for the details. I have added some defensive checks + logging around the area where this crash occurs. 

Here's the new binary with those checks: [Download](https://dl.typesense.org/releases/0.17.0.rc2/typesense-server-0.17.0.rc2-linux-amd64.tar.gz). Docker image is also available as `typesense/typesense:0.17.0.rc2`.

Can you please run the searches against those binaries and watch out for the error logs? Look out for the `Facet field type` message in the logs.

**Comment by mubibil** [comment] 2020-11-02 19:49
@kishorenc 
I think you are looking for these lines;
`E20201102 19:41:34.773066 17866 collection.cpp:1301] Facet field array size 8 lesser than array pos 19 for facet field tag
E20201102 19:41:34.773133 17866 collection.cpp:1303] Facet field type: string[]
E20201102 19:41:34.773180 17866 collection.cpp:1304] Actual document: {"brand":"Ola","cat":["gunluk-elbise"],"clicknum":3,"color":["Kırmızı"],"discount":21,"discount_range":["0.1_100","20_100"],"id":"83102","material":[],"name":"Kırmızı V Yaka Volanlı Mini Elbise","popularity":29605,"posi":83102,"price":63.99,"price_range":"50_100","product_tags":["Kırmızı","elbise","günlük elbise","Ola","Trendyol","gunluk-elbise","Kırmızı V Yaka Volanlı Mini Elbise"],"provider":"Trendyol","provider_id":2,"sale":"İndirimli","seo_link":"83102-ola-kirmizi-v-yaka-volanli-mini-elbise.html","size":["36","38","40"],"style":["Desenli"],"sub":[],"tag":["trendyol","ola","trendyol-elbise","ola-elbise","mini-elbise","desenli-elbise","kirmizi-elbise","indirimli-elbise"],"type":["Mini"]}`

**Comment by kishorenc** [comment] 2020-11-03 01:54
@mubibil 

Yes that's what I was looking for, thanks a lot. This patch logs the issue and moves on, instead of crashing. I'm now able to narrow down into the exact issue but I need some more information before I can reproduce it as a test case and fix it. 

1. I assume that this happens even on a fresh start against the dataset, correct (since you would have restarted the server with the new build)?
2. Can you please post the search query/request associated with the above log? Is it consistently reproducible? i.e. same query fails after a restart of the server?

If you don't have that query anymore, you can post another query along with the error logs associated with that. With the query I will get some more information as to what type of query params are triggering this behavior and hopefully with that, I can reproduce it. If that's not possible/tricky, let me know and I can generate another build with more logging to capture the query, along with those error logs.

**Comment by kishorenc** [comment] 2020-11-03 03:13
@mubibil Good news: I have managed to reproduce the issue locally. Will update you when I have the fix ready. Thanks for helping out!

**Comment by mubibil** [comment] 2020-11-03 05:41
@kishorenc 
Ready to help if needed.

**Comment by kishorenc** [comment] 2020-11-05 12:32
@mubibil Can you please check again against this build: [Download](https://dl.typesense.org/releases/0.17.0.rc3/typesense-server-0.17.0.rc3-linux-amd64.tar.gz).

Also published as `typesense/typesense:0.17.0.rc3`.

**Comment by mubibil** [comment] 2020-11-05 13:15
@kishorenc Everything seems ok. Thank you!

**Comment by kishorenc** [comment] 2020-11-05 15:18
👍 Great. Thank you for reporting this issue and helping to verify the fix. I will close this issue. Will be doing a point release with this fix.

**Closed by kishorenc** 2020-11-05 15:18 UTC
Labels: triage
