### ISSUE TITLE
exact match and phrase query supported?

### ISSUE THREAD

**Issue by bnfd** [typesense/typesense#272] opened 2021-05-19 12:18 UTC
Hi,

Are exact matches and phrase queries supported? 

By **exact match** I mean: the query "Harry Potter" book will force to have Harry and Potter to follow each other (without typo). 

By **phrase query** I mean: allow searching multiple words without a typo and distance between them. For example, the query "Harry Potter" book will force to have Harry and Potter to follow each other, have no typo and have the word book somewhere else on the document.

**Comment by kishorenc** [comment] 2021-05-20 01:47
👋 @bnfd We don't support exact searching yet, but that's on our prioritized feature backlog. We do support the "-" operator which you can use to exclude specific words in the search query. E.g. `sneakers -nike`.

**Comment by bnfd** [comment] 2021-05-20 13:00
Thank you. 
Is the roadmap available somewhere?

**Comment by bnfd** [comment] 2021-05-20 14:18
@kishorenc Just to make sure, this means that it is not possible to disable typo tolerance, right?

**Comment by jasonbosco** [comment] 2021-05-20 18:43
@bnfd The roadmap is not public at the moment, mainly because we actively shift things around depending on user feedback. But we plan to use Github milestones shortly to at least indicate what will be part of the upcoming version and may be the next one.

**Comment by bnfd** [comment] 2021-08-20 20:33
Are there any updates on "phrase match"?

**Comment by Sembiance** [comment] 2021-08-20 20:40
> Are there any updates on "phrase match"?

According to the blog post, `"phrase search"` is available in 0.21.0: https://blog.meilisearch.com/refactoring-meilisearch/

**Comment by jasonbosco** [comment] 2021-08-20 22:42
@Sembiance The document you linked to is not Typesense's documentation :)

"Phrase match" is high on our priority list, so we should be able to get to it in the next few months.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment] 2022-03-14 18:26
Which versions are the live demos using? I hope I can give the new feature a try.

**Comment by terreng** [comment] 2022-03-14 21:10
@jasonbosco I'm looking forward to this new feature, and I tried it out with the new RC version. However, it didn't work how I expected it to. I expected "phrase search" to work more like an exact match in that the words should all appear, in the right order, and in very close proximity. In my testing however, I found that while putting multiple words in quotes did seem to work at requiring that all of them appear at least once somewhere in the text, it unfortunately also included matches with the words in the wrong order and/or scattered throughout the text. For some searches, especially common words, using quotes actually made the results significantly worse, often completely missing documents with exact matches. Am I misunderstanding how phrase searching is supposed to work, or is it not working properly?

Thank you for your work on this. I'm impressed by the rapid rate of improvement on this product, and I hope to be able to use it in production soon.

**Comment by kishorenc** [comment] 2022-03-15 02:29
@terreng Can you please tell me the exact RC version you are using? We recently fixed the ordering issue and on the datasets I'm trying locally, it's working fine. Would you be able to share a sample dataset & query that reproduces the problem?

**Comment by terreng** [comment] 2022-03-15 02:35
@kishorenc I tried using 0.23.0.rc42. Is this the right version? Let me know if so and I'll try to put together a reduced test case. Otherwise, let me know how I can test the version with the fix. Thanks!

**Comment by kishorenc** [comment] 2022-03-15 02:55
RC42 is fine -- I'll appreciate a test case against that.

**Comment by terreng** [comment] 2022-03-16 21:16
@kishorenc I put together a small data set and example query that perfectly illustrates this issue.

The data set is transcripts of the top 20 most popular TED Talks on YouTube: [ted_talks.json](https://github.com/terreng/samples/blob/master/ted_talks.json)

Note that only one of the documents includes the exact phrase `have it be`. (document id zIwLWfaAg-8)


Here are the results for the search `have it be` _without_ quotes:

1. **zIwLWfaAg-8**: you could choose to <b>have</b> <b>it</b> <b>be</b> used only by friends
2. iCvmsMzlF7o: how we numb. And <b>it</b> doesn\'t just <b>have</b> to <b>be</b> addiction. The other thing
3. Ks-_Mh1QhMc: not that physician will <b>be</b> sued. So <b>it</b> doesn\'t <b>have</b> to do so much
4. arj7oStGLkU: like that. That would <b>be</b> the plan. I would <b>have</b> <b>it</b> all ready to go
5. P_6vDLq64gE: you don\'t want to <b>be</b> deceived, you <b>have</b> to know, what is <b>it</b> that you\'re hungry for?

As you can see, the document with the exact match is first, which is what I would expect.


Now here are the results for the search `"have it be"` (_with_ quotes):

1. 9kxL9Cf46VM: going." "Neither do I. <b>It</b> will <b>be</b> an adventure, sir." (Laughter)
2. 7jx0dTYUO5E: was an ultrasound, so <b>it</b> would <b>have</b> <b>been</b> moving images
3. iG9CE55wbtY: the sequel, you may <b>have</b> seen <b>it.</b> (Laughter) "Nativity II." But
4. 8KkKuTCFvzI: good relationships, they don\'t <b>have</b> to <b>be</b> smooth all the time.
5. **zIwLWfaAg-8**: you could choose to <b>have</b> <b>it</b> <b>be</b> used only by friends

Suddenly the document with the exact match drops down to the 5th result. This is not what I would expect, seeing as it is the only document with an exact match to the phrase. In this example, adding quotes has had the opposite effect as what I would expect. In the search with quotes, I don't believe the top 4 results should even be results at all, because none of them match the phrase.


<details>
  <summary>Example code (JavaScript)</summary>
  

  **Create collection**
  ```javascript
  client.collections().create({
      'name': 'ted_talks',
      'fields': [
          {'name': 'text', 'type': 'string' },
      ]
  }).then(function(data) {
      console.log(data)
  })
  ```

  **Add documents**
  ```javascript
  var ted_talks = JSON.parse(fs.readFileSync("ted_talks.json", "utf8"));
  
  var documents = Object.keys(ted_talks).map(function(a) {return {"id":a,"text":ted_talks[a]}});
  
  client.collections('ted_talks').documents().import(documents, {action: 'upsert'}).then(function(data) {
      console.log(data);
  })
  ```

  **Search**
  ```javascript
  client.collections('ted_talks').documents().search({
	  "q": "\"have it be\"",
	  "query_by": "text", 
	  "per_page": 5
  }).then(function(data) {
      console.log(data.hits.map(function(a) {return a.document.id+": "+a.highlights[0].snippet}));
  })
  ```
  
</details>


I ran this example using version 0.23.0.rc42.

**Comment by kishorenc** [comment] 2022-03-17 14:33
@terreng 

Thank you so much for putting this together. Can you please check against `0.23.0.rc47` -- it's fixed on this build.

**Comment by terreng** [comment] 2022-03-17 19:29
@kishorenc I tested it out and it does indeed appear to be working as expected now. I appreciate that you were able to fix this so quickly. Very excited for this feature. Thanks!

**Comment by zutamacka** [comment] 2022-05-19 14:09
OK, I'm hoping I didn't get this right.. :) 

I have a firebase database of files, and a TSense database of content per page. Each TSense entry contains the firebase ID of "their" file, something like Kjsdhgf23DSDFjja . Is there no way to make a query to TSense which will return ALL of the entries containing EXACTLY the same firebase ID?  

Would something like 
`        q: post.fireId,
        query_by: 'fireId',
        filter_by: `fireId:=${post.fireId}``
work?

**Comment by jasonbosco** [comment] 2022-05-19 15:26
@zutamacka 

> Is there no way to make a query to TSense which will return ALL of the entries containing EXACTLY the same firebase ID - all of the 87 pages but no extra pages?

You would have to use `filter_by`:

```
q=*, filter_by: fireId:=${post.fireId}
```

`q` and `query_by` are only for text based search queries that users type in. For structured search where the exact value is already known programmatically, you want to use filter_by.

**Comment by zutamacka** [comment] 2022-05-20 07:39
@jasonbosco  thank you so much!! :) :)

**Closed** 2022-06-19 05:27 UTC

**Comment by TuanMinPay** [comment] 2024-05-12 23:15
> @zutamacka
> 
> > Is there no way to make a query to TSense which will return ALL of the entries containing EXACTLY the same firebase ID - all of the 87 pages but no extra pages?
> 
> You would have to use `filter_by`:
> 
> ```
> q=*, filter_by: fireId:=${post.fireId}
> ```
> 
> `q` and `query_by` are only for text based search queries that users type in. For structured search where the exact value is already known programmatically, you want to use filter_by.

not work for me 😬

`(async () => {
  let rs = await client.collections("39_products").documents().search({
    q: "*",
    // query_by: "Codigo_Producto",
    filter_by: `Codigo_Producto:=12005051`,
    // prefix: false,
    // pre_segmented_query: true,
    // typo_tokens_threshold: 0,
    // num_typos: 0,
  });
  console.log("====================================");
  console.log(rs.hits[0] ? rs.hits[0].document.Codigo_Producto : "Not found", "12005051");
  console.log("====================================");
})();`
