### ISSUE TITLE
Search sort randomly

### ISSUE THREAD

**Issue by dipudey** [typesense/typesense#912] opened 2023-02-27 05:02 UTC
Hey,

Currently the logic for sort_by is:  sorting_field:desc

Is it possible to sort data randomly?

**Comment by jasonbosco** [comment] 2023-02-27 19:05
This is not possible to do. 

Here's a workaround: https://github.com/typesense/typesense/issues/637#issuecomment-1284261653

Duplicate of #637

**Closed by jasonbosco** 2023-02-27 19:05 UTC
