### ISSUE TITLE
Pagination returning the same results for every page

### ISSUE THREAD

**Issue by nonapod** [typesense/typesense#171] opened 2020-12-16 08:29 UTC
## Description

Every page in pagination results is the same when filtering by a facet and using grouped results.

## Steps to reproduce

The following is an example of a query on product pages, each product has a **sku** and a **group**, multiple skus are grouped together in a **group** and displayed on a product listing page.
`http://192.168.1.68:8108/collections/product_pages/documents/search?group_by=group&q=*&page=1&group_limit=1&filter_by=Color:Brown&per_page=24`

Every page returned, out of 3470 grouped results, is the same except for the last few pages.

## Expected Behavior

Expecting to see products grouped by their **group** field value, limited to 1 product per group, with different results for each page i.e. the first page of results will differ from the second and third page of results.

## Actual Behavior

Every single returned page result is the same.

## Metadata

**Typsense Version**:
v0.17.0

**OS**:
 Ubuntu 19.10

**Comment by nonapod** [comment] 2020-12-17 04:35
I've provided some sample results, with a slightly different query, reducing the number of items per page and limiting included fields for reference:

**query**
http://192.168.1.68:8108/collections/product_pages/documents/search?query_by=vendor&group_by=group&q=A19&group_limit=1&filter_by=Color:= Brown&per_page=5&page=1&include_fields=sku, group

**page 1**
`{
    "facet_counts": [],
    "found": 442,
    "grouped_hits": [
        {
            "group_key": [
                "LVMP08-BT"
            ],
            "hits": [
                {
                    "document": {
                        "group": "LVMP08-BT",
                        "sku": "LVMP08-BT"
                    },
                    "highlights": [
                        {
                            "field": "vendor",
                            "matched_tokens": [
                                "A19"
                            ],
                            "snippet": "<mark>A19</mark>"
                        }
                    ],
                    "text_match": 33488996
                }
            ]
        },
        {
            "group_key": [
                "LVMP07-DB-X"
            ],
            "hits": [
                {
                    "document": {
                        "group": "LVMP07-DB-X",
                        "sku": "LVMP07-DB-X"
                    },
                    "highlights": [
                        {
                            "field": "vendor",
                            "matched_tokens": [
                                "A19"
                            ],
                            "snippet": "<mark>A19</mark>"
                        }
                    ],
                    "text_match": 33488996
                }
            ]
        },
        {
            "group_key": [
                "LVMP06-SP-X"
            ],
            "hits": [
                {
                    "document": {
                        "group": "LVMP06-SP-X",
                        "sku": "LVMP06-SP-X"
                    },
                    "highlights": [
                        {
                            "field": "vendor",
                            "matched_tokens": [
                                "A19"
                            ],
                            "snippet": "<mark>A19</mark>"
                        }
                    ],
                    "text_match": 33488996
                }
            ]
        },
        {
            "group_key": [
                "LVMP01-SP-X"
            ],
            "hits": [
                {
                    "document": {
                        "group": "LVMP01-SP-X",
                        "sku": "LVMP01-SP-X"
                    },
                    "highlights": [
                        {
                            "field": "vendor",
                            "matched_tokens": [
                                "A19"
                            ],
                            "snippet": "<mark>A19</mark>"
                        }
                    ],
                    "text_match": 33488996
                }
            ]
        },
        {
            "group_key": [
                "LVMP01-BT-X"
            ],
            "hits": [
                {
                    "document": {
                        "group": "LVMP01-BT-X",
                        "sku": "LVMP01-BT-X"
                    },
                    "highlights": [
                        {
                            "field": "vendor",
                            "matched_tokens": [
                                "A19"
                            ],
                            "snippet": "<mark>A19</mark>"
                        }
                    ],
                    "text_match": 33488996
                }
            ]
        }
    ],
    "page": 1,
    "request_params": {
        "per_page": 5,
        "q": "A19"
    },
    "search_time_ms": 5
}`

**page 2**
`{
    "facet_counts": [],
    "found": 442,
    "grouped_hits": [
        {
            "group_key": [
                "LVMP08-BT"
            ],
            "hits": [
                {
                    "document": {
                        "group": "LVMP08-BT",
                        "sku": "LVMP08-BT"
                    },
                    "highlights": [
                        {
                            "field": "vendor",
                            "matched_tokens": [
                                "A19"
                            ],
                            "snippet": "<mark>A19</mark>"
                        }
                    ],
                    "text_match": 33488996
                }
            ]
        },
        {
            "group_key": [
                "LVMP07-DB-X"
            ],
            "hits": [
                {
                    "document": {
                        "group": "LVMP07-DB-X",
                        "sku": "LVMP07-DB-X"
                    },
                    "highlights": [
                        {
                            "field": "vendor",
                            "matched_tokens": [
                                "A19"
                            ],
                            "snippet": "<mark>A19</mark>"
                        }
                    ],
                    "text_match": 33488996
                }
            ]
        },
        {
            "group_key": [
                "LVMP06-SP-X"
            ],
            "hits": [
                {
                    "document": {
                        "group": "LVMP06-SP-X",
                        "sku": "LVMP06-SP-X"
                    },
                    "highlights": [
                        {
                            "field": "vendor",
                            "matched_tokens": [
                                "A19"
                            ],
                            "snippet": "<mark>A19</mark>"
                        }
                    ],
                    "text_match": 33488996
                }
            ]
        },
        {
            "group_key": [
                "LVMP01-SP-X"
            ],
            "hits": [
                {
                    "document": {
                        "group": "LVMP01-SP-X",
                        "sku": "LVMP01-SP-X"
                    },
                    "highlights": [
                        {
                            "field": "vendor",
                            "matched_tokens": [
                                "A19"
                            ],
                            "snippet": "<mark>A19</mark>"
                        }
                    ],
                    "text_match": 33488996
                }
            ]
        },
        {
            "group_key": [
                "LVMP01-BT-X"
            ],
            "hits": [
                {
                    "document": {
                        "group": "LVMP01-BT-X",
                        "sku": "LVMP01-BT-X"
                    },
                    "highlights": [
                        {
                            "field": "vendor",
                            "matched_tokens": [
                                "A19"
                            ],
                            "snippet": "<mark>A19</mark>"
                        }
                    ],
                    "text_match": 33488996
                }
            ]
        }
    ],
    "page": 2,
    "request_params": {
        "per_page": 5,
        "q": "A19"
    },
    "search_time_ms": 5
}`

**page 3**
`{
    "facet_counts": [],
    "found": 442,
    "grouped_hits": [
        {
            "group_key": [
                "LVMP08-BT"
            ],
            "hits": [
                {
                    "document": {
                        "group": "LVMP08-BT",
                        "sku": "LVMP08-BT"
                    },
                    "highlights": [
                        {
                            "field": "vendor",
                            "matched_tokens": [
                                "A19"
                            ],
                            "snippet": "<mark>A19</mark>"
                        }
                    ],
                    "text_match": 33488996
                }
            ]
        },
        {
            "group_key": [
                "LVMP07-DB-X"
            ],
            "hits": [
                {
                    "document": {
                        "group": "LVMP07-DB-X",
                        "sku": "LVMP07-DB-X"
                    },
                    "highlights": [
                        {
                            "field": "vendor",
                            "matched_tokens": [
                                "A19"
                            ],
                            "snippet": "<mark>A19</mark>"
                        }
                    ],
                    "text_match": 33488996
                }
            ]
        },
        {
            "group_key": [
                "LVMP06-SP-X"
            ],
            "hits": [
                {
                    "document": {
                        "group": "LVMP06-SP-X",
                        "sku": "LVMP06-SP-X"
                    },
                    "highlights": [
                        {
                            "field": "vendor",
                            "matched_tokens": [
                                "A19"
                            ],
                            "snippet": "<mark>A19</mark>"
                        }
                    ],
                    "text_match": 33488996
                }
            ]
        },
        {
            "group_key": [
                "LVMP01-SP-X"
            ],
            "hits": [
                {
                    "document": {
                        "group": "LVMP01-SP-X",
                        "sku": "LVMP01-SP-X"
                    },
                    "highlights": [
                        {
                            "field": "vendor",
                            "matched_tokens": [
                                "A19"
                            ],
                            "snippet": "<mark>A19</mark>"
                        }
                    ],
                    "text_match": 33488996
                }
            ]
        },
        {
            "group_key": [
                "LVMP01-BT-X"
            ],
            "hits": [
                {
                    "document": {
                        "group": "LVMP01-BT-X",
                        "sku": "LVMP01-BT-X"
                    },
                    "highlights": [
                        {
                            "field": "vendor",
                            "matched_tokens": [
                                "A19"
                            ],
                            "snippet": "<mark>A19</mark>"
                        }
                    ],
                    "text_match": 33488996
                }
            ]
        }
    ],
    "page": 3,
    "request_params": {
        "per_page": 5,
        "q": "A19"
    },
    "search_time_ms": 5
}`

**Comment by jasonbosco** [comment] 2020-12-18 07:08
@nonapod I wasn't able to replicate this issue with the dataset I have. Would you be able to share a small sample of your dataset, just enough to replicate this issue? If you're not able to share it on Github, could you email it to contact at typesense dot org?

**Comment by nonapod** [comment] 2020-12-20 08:04
hi @jasonbosco after more testing, and a fresh install, nuking data and reindexing, I'm still getting the issue, however it's not just limited to groups, but also just a regular select all query with paging seems to be returning duplicate page results, despite there not being duplicates of those items.

I've gone ahead and downloaded the source code for now, will get it set up and see if I can step through it and get it sorted, if not, I'll go ahead and toss a link to the dataset. I'll let you know!

**Comment by jasonbosco** [comment] 2020-12-21 16:30
@nonapod I now remember seeing this issue in the past when I accidentally indexed the same records twice due to a bug in my retry logic in the indexing script. This happened because I didn’t set an ID field in the record and so each retry was caused a new record to be created within Typesense with a different auto generated id field. Could this be the issue in your case as well? 

When you do a regular search, could you look at the ID field returned in the duplicate records?

**Comment by nonapod** [comment] 2020-12-22 07:29
hi @jasonbosco it looks like the IDs are set correctly as each page of results return the same id, also the total number of documents is correct to the amount indexed (this is all indexed via the Gatsby plugin). To confirm that this isn't just a Gatsby issue, I'll try indexing the same items via a quick Python script to see whether or not the issue is contained to the Gatsby plugin or not.

**Comment by nonapod** [comment] 2020-12-23 21:19
@jasonbosco I went ahead and ran a few tests on the Debian packages for both **0.16.1** and **0.17.0** on two different Linux boxes and ran a script on each of these using Gatsby and also a manual Python script to index product data. Further to this, I also ran a test script to index a simple dictionary of words with 1 field on it, all instances seem to return strange page results, with the first page being correct and a large amount of succeeding pages being duplicated. 

I have a test server over here **ts.gepid.me** with the following search auth key: **WP0l98krWsN9sV3rlV2gCdVU5hy0aD8t**
the collection is called **words**, which contains a simple indexed dictionary of words. The behavior visible with paging has been the same in every test so far on both of those Debian packages.

Here's a few of the query examples
http://ts.gepid.me/collections/words/documents/search?q=*&items_per_page=1&page=1
http://ts.gepid.me/collections/words/documents/search?q=*&items_per_page=1&page=2
http://ts.gepid.me/collections/words/documents/search?q=*&items_per_page=1&page=3
http://ts.gepid.me/collections/words/documents/search?q=*&items_per_page=1&page=4

Anything after page 2 seems to be duplicated, yet the items have the same ID and only contain one indexed item.

Tempted to debug this however I've been a little reluctant to setup docker locally thus far, to avoid the bloat on the local machine, but can do if necessary. However it'd be good to know if maybe I'm just doing something wrong beforehand.

**Comment by jasonbosco** [comment] 2020-12-23 21:55
@nonapod I was able to replicate the issue as well. Taking a closer look, I'll keep you posted.

**Comment by jasonbosco** [comment] 2020-12-24 04:04
@nonapod Would you be able to export this dataset from the cluster (`GET http://ts.gepid.me/collections/words/documents/export -H 'x-typesense-api-key: <admin-key>' > export.json `), gzip it and send it over email to contact at typesense dot org, along with the schema definition?

**Comment by nonapod** [comment] 2020-12-24 20:49
hi @jasonbosco I went ahead and emailed you the schema and a data export containing 100,000 words. Also, I created a quick Python script (Python 3, requires typesense). This will create (or delete and create) the Words collection, populate it with 2500 words and the run a unit test to see if the pagination results are duplicating. The script parameters can be edited at the bottom of the script in the "main" block:

`import typesense
import unittest
import urllib.request
from typesense.exceptions import ObjectNotFound

WORDS_FILE_URL = "https://raw.githubusercontent.com/dwyl/english-words/master/words.txt"


def getSearch(api_key: str, host: str = "127.0.0.1", port: str = "8108", protocol: str = "http",
              timeout: int = 3) -> typesense.Client:
    """
    Gets a Typesense client.

    :param api_key: Typesense api key.
    :param host: Host, default ot localhost.
    :param port: Port, default to 8108.
    :param protocol: Protocol, defaults to http.
    :param timeout: Connection timeout in seconds, defaults to 3.

    :return typesense.Client: Returns a Typesense client.
    """
    return typesense.Client({
        'nodes': [{
            'host': host,
            'port': port,
            'protocol': protocol
        }],
        'api_key': api_key,
        'connection_timeout_seconds': timeout,
    })


def getWordSchema(collection_name: str = "words") -> dict:
    """
    Gets the word schema.

    :param collection_name: A name to give to the collection.

    :return dict: The schema.
    """
    return {
        "name": collection_name,
        "fields": [
            {
                "name": "word",
                "type": "string"
            },
            {
                "name": "word_priority_score",
                "type": "int32",
            },
        ],
        "default_sorting_field": "word_priority_score",
    }


def createTestWords(collection_name: str = "words", max_words: int = None):
    """
    Inserts dictionary words into a Typesense collection.

    :param collection_name: The Typesense collection name.
    :param max_words: A maximum number of words to add.
    """

    # Delete the test schema if it's there.
    try:
        print("Deleting collection {}...".format(collection_name))
        client.collections[collection_name].delete()
    except ObjectNotFound:
        print("No existing collection found with name {}.".format(collection_name))
        pass

    # Create the schema.
    print("Creating collection {}...".format(collection_name))
    client.collections.create(getWordSchema(collection_name))
    print("Created collection {}.".format(collection_name))

    words = [line.strip() for line in urllib.request.urlopen(WORDS_FILE_URL).read().decode("utf-8").split("\n")]

    if max_words:
        print("{} Words found, indexing a maximum of {}...".format(len(words), max_words))
    else:
        print("{} Words found, indexing all...".format(len(words)))

    for i, word in enumerate(words):
        if max_words and i >= max_words:
            break

        client.collections[collection_name].documents.create({
            "id": str(i),
            "word": word,
            "word_priority_score": 10,
        })

    print("Indexing complete.")


class TestPagination(unittest.TestCase):
    api_key = ""
    host = "127.0.0.1"
    port = "8108"
    protocol = "http"
    collection_name = "words"
    timeout = 3
    max_pages = 10
    items_per_page = 10

    def test_pagination_duplication(self):
        """
        Tests to see if the pagination results duplicate.
        """
        previous_hits = []
        client = getSearch(api_key=self.api_key, host=self.host, port=self.port, protocol=self.protocol, timeout=3)

        for page in range(1, self.items_per_page + 1):
            result = client.collections[self.collection_name].documents.search({
                "q": "*",
                "items_per_page": self.items_per_page,
                "page": page,
            })

            if not result or "hits" not in result:
                break
            if previous_hits:
                msg = "Duplicate hits found starting at page {}.".format(page)
                self.assertNotEqual(result["hits"], previous_hits, msg)
            previous_hits = result["hits"]


if __name__ == "__main__":
    API_KEY = "API KEY GOES HERE"
    COLLECTION = "words"
    HOST = "127.0.0.1"
    PORT = "8108"
    PROTOCOL = "http"
    TIMEOUT = 3
    MAX_WORDS = 2500
    MAX_PAGES = 10
    ITEMS_PER_PAGE = 10

    # Index up to a maximum amount of words.
    client = getSearch(api_key=API_KEY, host=HOST, port=PORT, protocol=PROTOCOL, timeout=TIMEOUT)
    createTestWords(collection_name=COLLECTION, max_words=MAX_WORDS)

    # Set variables for test case.
    TestPagination.host = HOST
    TestPagination.api_key = API_KEY
    TestPagination.collection_name = COLLECTION
    TestPagination.port = PORT
    TestPagination.protocol = PROTOCOL
    TestPagination.timeout = TIMEOUT
    TestPagination.max_pages = MAX_PAGES
    TestPagination.items_per_page = ITEMS_PER_PAGE

    # Run the tests.
    unittest.main()`

**Comment by jasonbosco** [comment] 2020-12-26 18:44
Summarizing our email conversation here for posterity: this is a regression with v0.17.0. The fix is available in v0.18 which will be released publicly in a week or so.

In the meantime, here’s an RC build with the fix: https://dl.typesense.org/releases/0.18.0.rc14/typesense-server-0.18.0.rc14-linux-amd64.tar.gz

**Comment by jasonbosco** [comment] 2020-12-29 04:24
Just released v0.18.0 with this fix: https://github.com/typesense/typesense/releases/tag/v0.18.0

**Closed by jasonbosco** 2020-12-29 04:24 UTC
Labels: bug, fix-available
